### ISSUE TITLE
DDC & Dart2JS error on stable building tests for platform chrome

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1161]
https://travis-ci.org/flutter/devtools/jobs/596339814

Excerpts:
```
Error creating devtools_app|test/inspector_service_test.ddc.dill
Error creating devtools_app|test/inspector_service_test.dart.vm_test.ddc.dill
Error compiling dartdevc module:devtools_app|test/browser/tables_test.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
```

```
Crash when compiling test/support/cli_test_driver.dart,
at character offset null:
Unexpected Kernel version 35 (expected 29).
#0      BinaryBuilder.readComponent
(package:kernel/binary/ast_from_binary.dart:450:7)
#1      ProcessedOptions.loadComponent
(package:front_end/src/base/processed_options.dart:393:10)
#2      ProcessedOptions.loadInputSummaries.<anonymous closure>
(package:front_end/src/base/processed_options.dart:355:35)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      ProcessedOptions.loadInputSummaries
(package:front_end/src/base/processed_options.dart:355:67)
<asynchronous suspension>
#6      generateKernelInternal.<anonymous closure>
(package:front_end/src/kernel_generator_impl.dart:95:50)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#8      generateKernelInternal
(package:front_end/src/kernel_generator_impl.dart:69:10)
```

**Comment by DaveShuckerow** [comment]
Bots now passing with #1163.
