### ISSUE TITLE
Tests are timing out on Travis

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1311]
Our tests are timing out on Travis

From https://travis-ci.org/flutter/devtools/jobs/608317110#L478:

```
+flutter test test/cpu_profile_model_test.dart test/cpu_profile_transformer_test.dart test/enum_utils_test.dart test/geometry_test.dart test/info_controller_test.dart test/inspector_controller_test.dart test/inspector_data_models_test.dart test/inspector_service_test.dart test/logging_controller_test.dart test/memory_service_test.dart test/service_manager_test.dart test/stream_value_listenable_test.dart test/tables_test.dart test/timeline_controller_test.dart test/timeline_model_test.dart test/timeline_protocol_test.dart test/trees_test.dart test/tree_test.dart test/url_utils_test.dart test/utils_test.dart test/version_test.dart test/viewport_canvas_test.dart test/core/ test/fixtures/ test/flutter/ test/support/ test/ui/
05:23 +34 ~1 -1: /home/travis/build/flutter/devtools/packages/devtools_app/test/logging_controller_test.dart: logging controller tests structured errors [E]
  TimeoutException after 0:04:00.000000: Test timed out after 4 minutes.
  package:test_api  Invoker._onRun.<fn>.<fn>.<fn>
  
07:50 +39 ~1 -2: /home/travis/build/flutter/devtools/packages/devtools_app/test/service_manager_test.dart: serviceManagerTests toggle boolean service extension [E]
  TimeoutException after 0:02:00.000000: Test timed out after 2 minutes.
  package:test_api  Invoker._onRun.<fn>.<fn>.<fn>
  
11:52 +45 ~1 -3: /home/travis/build/flutter/devtools/packages/devtools_app/test/service_manager_test.dart: serviceManagerTests - restoring device-enabled extension: all extension types [E]
  TimeoutException after 0:04:00.000000: Test timed out after 4 minutes.
  package:test_api  Invoker._onRun.<fn>.<fn>.<fn>
  
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

This is happens at this flutter `(Channel master, v1.10.15-pre.425, on Linux, locale en_US.UTF-8)`:

```
+flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.425, on Linux, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```

**Comment by DaveShuckerow** [comment]
This known breaking change to the flutter engine may be related: https://github.com/flutter/flutter/pull/39945

The failing tests are all attempting to talk to running apps, and the above may be affecting their lifecycle.

**Comment by DaveShuckerow** [comment]
Now tests are failing with a new error.

From https://travis-ci.org/flutter/devtools/jobs/608382146#L626:

```
Error creating devtools_app|lib/src/auto_dispose.ddc.dill
Error creating kernel summary for
module:devtools_app|lib/src/auto_dispose.ddc.dill
...
org-dartlang-app:///packages/html_shim/html.dart: Internal problem: Unhandled
Null in finalizeExports.
#0      internalProblem (package:front_end/src/fasta/problems.dart:46:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:59:10)
#2      DillLibraryBuilder.finalizeExports
(package:front_end/src/fasta/dill/dill_library_builder.dart:300:9)
#3      DillLibraryBuilder.ensureLoaded
(package:front_end/src/fasta/dill/dill_library_builder.dart:121:7)
#4      LazyLibraryScope.ensureScope
(package:front_end/src/fasta/dill/dill_library_builder.dart:72:20)
#5      LazyScope._local (package:front_end/src/fasta/scope.dart:461:5)
#6      Scope.forEach (package:front_end/src/fasta/scope.dart:358:5)
#7      Import.finalizeImports (package:front_end/src/fasta/import.dart:72:26)
#8      SourceLibraryBuilder.addImportsToScope
(package:front_end/src/fasta/source/source_library_builder.dart:1030:14)
#9      SourceLoader.computeLibraryScopes.<anonymous closure>
(package:front_end/src/fasta/source/source_loader.dart:437:23)
#10     _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:377:8)
#11     SourceLoader.computeLibraryScopes
(package:front_end/src/fasta/source/source_loader.dart:434:14)
#12     KernelTarget.buildOutlines.<anonymous closure>
(package:front_end/src/fasta/kernel/kernel_target.dart:256:14)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildOutlines
(package:front_end/src/fasta/kernel/kernel_target.dart:249:12)
<asynchronous suspension>
#15     IncrementalCompiler.computeDelta.<anonymous closure>
(package:front_end/src/fasta/incremental_compiler.dart:359:52)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#17     new Future.sync (dart:async/future.dart:222:31)
#18     CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:19)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     CompilerContext.runInContext
(package:front_end/src/fasta/compiler_context.dart:122:12)
#24     IncrementalCompiler.computeDelta
(package:front_end/src/fasta/incremental_compiler.dart:151:20)
<asynchronous suspension>
#25     computeKernel
(file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.d
art:320:10)
<asynchronous suspension>
#26     KernelWorker.performRequest
(file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.d
art:69:26)
<asynchronous suspension>
#27     AsyncWorkerLoop.run.<anonymous closure>
(package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AsyncWorkerLoop.run
(package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#33     main
(file:///b/s/w/ir/cache/builder/src/third_party/dart/utils/bazel/kernel_worker.d
art:38:48)
<asynchronous suspension>
#34     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:301:32)
#35     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by sigmundch** [comment]
This error looks very similar to that in https://github.com/dart-lang/sdk/issues/38794, but the "Null" seems odd here.

By any chance do you have simple steps we could use to reproduce this locally?

(FYI @johnniwinther - this may be a CFE issue)

**Comment by DaveShuckerow** [comment]
`flutter test --platform chrome` in `devtools/packages/devtools_app` should be able to reproduce this.

The command that fails in the test environment is

```
$ flutter test --platform chrome test/*.dart test/{core,fixtures,flutter,support,ui}/
```

**Comment by DaveShuckerow** [comment]
Everyone, note that this is only affecting linux builds of the unit tests.  The Mac builds do appear to be working.  On account of this, you can submit code if it passes the mac unit tests.

**Comment by devoncarew** [comment]
> Everyone, note that this is only affecting linux builds of the unit tests. The Mac builds do appear to be working. On account of this, you can submit code if it passes the mac unit tests.

Instead of landing on red, I'd suggest changing the travis setup to allow failures on that specific bot (https://github.com/flutter/devtools/blob/master/.travis.yml#L47), and planning to revert once the linux builds are working again.

**Comment by DaveShuckerow** [comment]
> Instead of landing on red, I'd suggest changing the travis setup to allow failures on that specific bot

Good suggestion.

**Comment by DaveShuckerow** [comment]
Bots are passing again.
