### ISSUE TITLE
Scaffold.of() error on flutter desktop

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1315]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold.
No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
There are several ways to avoid this problem. The simplest is to use a Builder to get a context that is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
  https://api.flutter.dev/flutter/material/Scaffold/of.html
A more efficient solution is to split your build function into several widgets. This introduces a new context from which you can obtain the Scaffold. In this solution, you would have an outer widget that creates the Scaffold populated by instances of your new inner widgets, and then in these inner widgets you would use Scaffold.of().
A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
The context used was:
  Initializer
#0      Scaffold.of (package:flutter/src/material/scaffold.dart:1313:5)
#1      showErrorSnackBar.<anonymous closure> (package:devtools_app/src/flutter/common_widgets.dart:139:14)
#2      FrameworkCore.initVmService (package:devtools_app/src/framework/framework_core.dart:60:22)
<asynchronous suspension>
#3      _InitializerState._attemptUrlConnection (package:devtools_app/src/flutter/initializer.dart:79:43)
<asynchronous suspension>
#4      _InitializerState.initState (package:devtools_app/src/flutter/initializer.dart:71:7)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4085:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
#75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#103    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#108    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#115    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#121    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#122    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
#123    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#126    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4939:32)
#127    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5281:17)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#129    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:605:16)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:4143:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#137    ProxyElement.update (package:flutter/src/widgets/framework.dart:4277:5)
#138    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5172:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:4143:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5172:14)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5172:14)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#152    StatelessElement.update (package:flutter/src/widgets/framework.dart:4033:5)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
#154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#156    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2347:33)
#157    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#158    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#159    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1097:15)
#160    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1036:9)
#161    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:5)
#162    _rootRun (dart:async/zone.dart:1124:13)
#163    _CustomZone.run (dart:async/zone.dart:1021:19)
#164    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#165    _invoke (dart:ui/hooks.dart:259:10)
#166    _drawFrame (dart:ui/hooks.dart:217:3)
```

**Comment by kenzieschmoll** [comment]
This is still happening
