### ISSUE TITLE
[Story of Your Layout] NoSuchMethodError

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1431]
This occurred on master:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _StoryOfYourFlexWidgetState#9cfef(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1112:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1147:6)
#2      _StoryOfYourFlexWidgetState._updateHighlighted (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:306:5)
#3      _StoryOfYourFlexWidgetState._setProperties (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:317:5)
#4      _StoryOfYourFlexWidgetState._onInspectorSelectionChanged (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:299:7)
<asynchronous suspension>
#5      _StoryOfYourFlexWidgetState._updateObjectGroupManager (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:370:5)
#6      _StoryOfYourFlexWidgetState.initState (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:226:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4356:58)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4207:5)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4382:11)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4207:5)
#21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5446:14)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5446:14)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4207:5)
#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4207:5)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#40     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4618:11)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4207:5)
#46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4382:11)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4207:5)
#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4202:5)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3197:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2991:12)
#56     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1288:36)
#57     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1220:34)
#58     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1251:23)
#59     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1191:7)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#65     StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#67     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5162:32)
#68     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5565:17)
#69     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:202:11)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#79     StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#85     StatefulElement.update (package:flutter/src/widgets/framework.dart:4414:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#91     StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#95     ProxyElement.update (package:flutter/src/widgets/framework.dart:4558:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#103    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#107    StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:4414:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#115    StatefulElement.update (package:flutter/src/widgets/framework.dart:4414:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#119    StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:4414:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#127    StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4414:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:4558:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#137    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5162:32)
#138    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5565:17)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#142    ProxyElement.update (package:flutter/src/widgets/framework.dart:4558:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#146    StatefulElement.update (package:flutter/src/widgets/framework.dart:4414:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#150    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#154    StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4244:16)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:3948:5)
#158    StatelessElement.update (package:flutter/src/widgets/framework.dart:4299:5)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#160    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5453:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#162    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5162:32)
#163    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5565:17)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:2980:15)
#165    _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:115:18)
#166    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2415:19)
#167    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:95:11)
#168    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
#169    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:919:15)
#170    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
#171    RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:173:5)
#172    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:240:5)
#173    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#174    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
#175    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#176    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
#177    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
#178    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
#179    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1628:7)
#180    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:888:18)
#181    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:401:19)
#182    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:13)
#183    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#184    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1103:15)
#185    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1042:9)
#186    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:5)
#187    _rootRun (dart:async/zone.dart:1126:13)
#188    _CustomZone.run (dart:async/zone.dart:1023:19)
#189    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#190    _invoke (dart:ui/hooks.dart:259:10)
#191    _drawFrame (dart:ui/hooks.dart:217:3)


════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building LayoutBuilder:
The getter 'hasBoundedHeight' was called on null.
Receiver: null
Tried calling: hasBoundedHeight

The relevant error-causing widget was: 
  LayoutBuilder file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/lib/src/inspector/flutter/story_of_your_layout/flex.dart:629:26
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      LayoutProperties.describeHeightConstraints (package:devtools_app/src/inspector/flutter/inspector_data_models.dart:166:24)
#2      _visualizeWidthAndHeightWithConstraints (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:108:26)
#3      _StoryOfYourFlexWidgetState._visualizeFlex (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:479:12)
#4      _StoryOfYourFlexWidgetState._buildLayout (package:devtools_app/src/inspector/flutter/story_of_your_layout/flex.dart:674:22)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
<img width="1139" alt="Screen Shot 2019-12-04 at 8 10 31 AM" src="https://user-images.githubusercontent.com/43759233/70159583-012a8980-166e-11ea-9570-d4bb7aede0c4.png">

**Comment by kenzieschmoll** [comment]
@albertusangga
