### ISSUE TITLE
BoxConstraints has negative minimum width with large amounts of flame chart data

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1503]
![image](https://user-images.githubusercontent.com/14947366/71607348-62d6fa00-2b2d-11ea-8dfc-12515f2e5fe7.png)

It's fixable by normalizing the bounds, fairly simple.

**Comment by DaveShuckerow** [comment]
Detailed error:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Container-[<'isolates/247789373073031-983'>](centerLeft,
flutter: padding: EdgeInsets(6.0, 0.0, 6.0, 0.0), bg: BoxDecoration(color: Instance of 'ThemedColor'),
flutter: constraints: BoxConstraints(w=-0.2, h=25.0; NOT NORMALIZED), dirty):
flutter: BoxConstraints has a negative minimum width.
flutter: The offending constraints were:
flutter:   BoxConstraints(w=-0.2, h=25.0; NOT NORMALIZED)
flutter: 
flutter: The relevant error-causing widget was:
flutter:   Container-[<'isolates/247789373073031-983'>]
flutter:   file:///Users/djshuckerow/Code/github.com/DaveShuckerow/devtools/packages/devtools_app/lib/src/charts/flutter/flame_chart.dart:346:18
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:514:9)
flutter: #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:543:19)
flutter: #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:562:6)
flutter: #3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:2163:27)
```

The rects are constructed with calls to `Rect.fromLTRB` , which suggests that the calculation of left and right values are sometimes giving values for `left` greater than the values for `right`.

That computation is done here:

https://github.com/flutter/devtools/blob/7c92de2ba30fc643ab183afc2f78ceaebdbf61fb/packages/devtools_app/lib/src/timeline/flutter/timeline_flame_chart.dart#L140-L145
