### ISSUE TITLE
Any Flutter integration test fails with import_export added.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#1637]
The test **test/flutter/integration/dart_cli_profile_test.dart** fails post the [PR](https://github.com/flutter/devtools/pull/1631).  Any integration test that just spins up and exits will fail with this assertion:

```
The following assertion was thrown while finalizing the widget tree:
496'package:flutter/src/widgets/overlay.dart': Failed assertion: line 132 pos 12: '_overlay != null':
497is not true.
498
499When the exception was thrown, this was the stack:
500#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:132:12)
501#3      NotificationsState.dispose (package:devtools_app/src/flutter/notifications.dart:89:19)
502#4      ImportController.dispose (package:devtools_app/src/config_specific/flutter/import_export/import_export.dart:23:21)
503#5      DevToolsScaffoldState.dispose (package:devtools_app/src/flutter/scaffold.dart:125:23)
504#6      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4700:12)
505#7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
506#8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
507#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
508#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
509#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
510#12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
511#13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
512#14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
513#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
514#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
515#17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
516#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
517#19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
518#20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
519#21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
520#22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
521#23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
522#24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
523#25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
524#26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
525#27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
526#28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
527#29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
528#30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
529#31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
530#32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
531#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
532#34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
533#35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
534#36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
535#37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
536#38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
537#39     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
538#40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
539#41     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
540#42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
541#43     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
542#44     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
543#45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
544#46     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
545#47     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
546#48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
547#49     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
548#50     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
549#51     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
550#52     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
551#53     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
552#54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
553#55     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
554#56     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
555#57     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
556#58     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
557#59     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
558#60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
559#61     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
560#62     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
561#63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
562#64     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
563#65     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
564#66     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
565#67     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
566#68     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
567#69     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
568#70     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
569#71     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
570#72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
571#73     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
572#74     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
573#75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
574#76     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
575#77     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
576#78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
577#79     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
578#80     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
579#81     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
580#82     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
581#83     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
582#84     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5839:16)
583#85     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
584#86     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
585#87     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
586#88     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
587#89     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
588#90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
589#91     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
590#92     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
591#93     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
592#94     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
593#95     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
594#96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
595#97     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
596#98     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
597#99     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
598#100    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
599#101    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
600#102    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5734:14)
601#103    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
602#104    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
603#105    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
604#106    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
605#107    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
606#108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
607#109    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
608#110    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
609#111    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
610#112    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
611#113    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
612#114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
613#115    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
614#116    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
615#117    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
616#118    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
617#119    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
618#120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
619#121    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
620#122    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
621#123    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4527:14)
622#124    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
623#125    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
62403:12 +204 ~1 -1: /home/travis/build/flutter/devtools/packages/devtools_app/test/flutter/integration/dart_cli_profile_test.dart: Whole app connects to a dart app [E]
625  Test failed. See exception logs above.
626  The test description was: connects to a dart app
627
```

**Comment by terrylucas** [comment]
Temporarily worked about the problem notifications being removed twice see [PR](https://github.com/flutter/devtools/pull/1638).
