### ISSUE TITLE
Possible to shrink the flexsplitcolumn too far

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1786]
Sliding one child up into the one above it, I can get this:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LayoutBuilder:
flutter: 'package:devtools_app/src/flutter/split.dart': Failed assertion: line 127 pos 14: 'size >=
flutter: _minSizeForIndex(index)': is not true.
flutter: 
flutter: The relevant error-causing widget was:
flutter:   LayoutBuilder
flutter:   file:///Users/djshuckerow/Code/github.com/DaveShuckerow/devtools/packages/devtools_app/lib/src/flutter/split.dart:105:12
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      _SplitState._buildLayout._sizeForIndex (package:devtools_app/src/flutter/split.dart:127:14)
flutter: #3      _SplitState._buildLayout.<anonymous closure> (package:devtools_app/src/flutter/split.dart:133:71)
flutter: #4      new List.generate (dart:core/list.dart:164:28)
flutter: #5      _SplitState._buildLayout (package:devtools_app/src/flutter/split.dart:133:24)
flutter: #6      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:100:33)
flutter: #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
flutter: #8      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:96:11)
flutter: #9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
flutter: #10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
flutter: #11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
flutter: #12     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:174:5)
flutter: #13     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:244:5)
flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #15     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:246:13)
flutter: #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #17     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
flutter: #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #21     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:266:13)
flutter: #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #23     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:746:15)
flutter: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #25     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:246:13)
flutter: #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #27     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:808:17)
flutter: #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #29     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:394:13)
flutter: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #31     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
flutter: #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #37     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:246:18)
flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #39     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:135:11)
flutter: #40     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:168:11)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #42     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:452:13)
flutter: #43     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1444:12)
flutter: #44     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1353:20)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #64     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
flutter: #65     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
flutter: #66     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
flutter: #67     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #72     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
flutter: #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #93     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3225:13)
flutter: #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #95     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
flutter: #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #103    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
flutter: #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
flutter: #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #109    RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
flutter: #110    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
flutter: #111    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
flutter: #112    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
flutter: #113    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
flutter: #114    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #115    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #116    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #117    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
flutter: (elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
flutter: 
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jacob314** [comment]
Fixed by https://github.com/flutter/devtools/commit/d03db3111fac9b9b478279813c689b0073a3501e
