### ISSUE TITLE
Support debugging standalone Dart applications

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#1809]
The left pane throws the following exception when trying to debug a Dart application:

```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 76 pos 16: 'keys.isNotEmpty':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new KeySet.fromSet 
package:flutter/…/widgets/shortcuts.dart:76
flutter: #3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
flutter: #4      new LogicalKeySet.fromSet 
package:flutter/…/widgets/shortcuts.dart:180
flutter: #5      ShortcutManager.handleKeypress 
package:flutter/…/widgets/shortcuts.dart:299
flutter: #6      _ShortcutsState._handleOnKey 
package:flutter/…/widgets/shortcuts.dart:461
flutter: #7      FocusManager._handleRawKeyEvent 
package:flutter/…/widgets/focus_manager.dart:1555
flutter: #8      RawKeyboard._handleKeyEvent 
package:flutter/…/services/raw_keyboard.dart:531
flutter: #9      BasicMessageChannel.setMessageHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:74
flutter: #10     _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:218
flutter: #11     _invoke3.<anonymous closure>  (dart:ui/hooks.dart:290:15)
flutter: #15     _invoke3  (dart:ui/hooks.dart:289:10)
flutter: #16     _dispatchPlatformMessage  (dart:ui/hooks.dart:164:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by bkonyi** [comment]
cc @kenzieschmoll

**Comment by devoncarew** [comment]
@bkonyi - I don't see this issue from the Flutter web version of the app at master.

**Comment by bkonyi** [comment]
> @bkonyi - I don't see this issue from the Flutter web version of the app at master.

I saw this in the OSX version, but maybe this has been fixed already?

**Comment by devoncarew** [comment]
They've been a lot of changes recently. We can keep this open for a bit, and re-test it once more of the debugger is ported over.

**Comment by kenzieschmoll** [comment]
closing as obsolete
