### ISSUE TITLE
Cannot read property 'children' of null in Layout Explorer

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1938]
Selected a bunch of different nodes in the inspector, opened layout explorer, switched pages in DevTools, came back to the inspector with the layout explorer open and selected a new node in the summary tree:

Was running on flutter web so the stack trace is a bit funky, but I'm pretty sure it is because we try to call `json['children']` when `RemoteDiagnosticsNode.json` is null. 
```
TypeError: Cannot read property 'children' of null
    at http://localhost:62153/packages/devtools_app/src/flutter/connect_screen.dart.lib.js:50690:60
    at flex$._FlexLayoutExplorerWidgetState.new.setState (http://localhost:62153/packages/flutter/src/widgets/widget_span.dart.lib.js:14710:22)
    at flex$._FlexLayoutExplorerWidgetState.new.[_updateHighlighted] (http://localhost:62153/packages/devtools_app/src/flutter/connect_screen.dart.lib.js:50685:12)
    at flex$._FlexLayoutExplorerWidgetState.new.[_setProperties] (http://localhost:62153/packages/devtools_app/src/flutter/connect_screen.dart.lib.js:50696:31)
    at flex$._FlexLayoutExplorerWidgetState.new.onSelectionChanged (http://localhost:62153/packages/devtools_app/src/flutter/connect_screen.dart.lib.js:50602:31)
    at onSelectionChanged.next (<anonymous>)
```

**Comment by elliette** [comment]
I'm guessing this is no longer reproducible, with the null-safety migration `json` can never be `null`:
 https://github.com/flutter/devtools/blob/95e2baae469fb6361ee7aec792e129626b0db9f9/packages/devtools_app/lib/src/shared/diagnostics/diagnostics_node.dart#L105
