### ISSUE TITLE
Graphical issues on inspector page after navigating to other tabs

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#1961]
I see weird issues like these (minus the tree icon position which is correct) after switching between tabs then going back to the inspector page.

![html](https://user-images.githubusercontent.com/1078012/81939048-b8e49f80-95ed-11ea-92ed-a109e76043f8.png)

I'm not sure it's related, but I also had this spat out to the console (I'm using latest Flutter master as of just now):

```
Error: Assertion failed: file:///Users/danny/Dev/Google/devtools/packages/devtools_app/lib/src/utils.dart:420:14
_start == null
is not true
    at Object.throw_ [as throw] (http://localhost:55076/dart_sdk.js:4461:11)
    at Object.assertFailed (http://localhost:55076/dart_sdk.js:4410:15)
    at utils.TimeRange.new.set start [as start] (http://localhost:55076/packages/devtools_app/src/utils.dart.lib.js:405:43)
    at timeline_processor.TimelineProcessor.new.processTimeline (http://localhost:55076/packages/devtools_app/src/flutter/connect_screen.dart.lib.js:57701:22)
    at processTimeline.next (<anonymous>)
    at http://localhost:55076/dart_sdk.js:36903:33
    at _RootZone.runUnary (http://localhost:55076/dart_sdk.js:36757:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55076/dart_sdk.js:31921:29)
    at handleValueCallback (http://localhost:55076/dart_sdk.js:32462:49)
    at Function._propagateToListeners (http://localhost:55076/dart_sdk.js:32494:17)
    at _Future.new.[_complete] (http://localhost:55076/dart_sdk.js:32337:25)
    at http://localhost:55076/dart_sdk.js:31501:30
    at internalCallback (http://localhost:55076/dart_sdk.js:23294:11)Error: Assertion failed: file:///Users/danny/Dev/Google/devtools/packages/devtools_app/lib/src/utils.dart:420:14
```

**Comment by kenzieschmoll** [comment]
The assertion error you are seeing will be fixed by https://github.com/flutter/devtools/pull/1962
