### ISSUE TITLE
Can't run devtools flutter web

### ISSUE THREAD

**Issue by bl4ckck** [flutter/devtools#1998]
```
flutter run -d chrome
v
```

### Results
```
Invalid argument (Expandos are not allowed on strings, numbers, booleans or null): null
#0      Expando._checkType (dart:core-patch/expando_patch.dart:141:7)
#1      Expando.[] (dart:core-patch/expando_patch.dart:20:5)
#2      FlutterVmService.httpAddress (package:flutter_tools/src/vmservice.dart:398:45)
#3      ResidentRunner.launchDevTools (package:flutter_tools/src/resident_runner.dart:1149:40)
<asynchronous suspension>
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1497:32)
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1526:13)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#24     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:256:17)
#25     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:242:5)
#26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#34     _StreamController._add (dart:async/stream_controller.dart:655:7)
#35     _StreamController.add (dart:async/stream_controller.dart:597:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#37     _rootRunUnary (dart:async/zone.dart:1206:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#43     _StreamController._add (dart:async/stream_controller.dart:655:7)
#44     _StreamController.add (dart:async/stream_controller.dart:597:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

### Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.19.0-2.0.pre.133, on Microsoft Windows [Version 10.0.18363.836], locale en-ID)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.45.1)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by devoncarew** [comment]
@bl4ckck - you're running this from a recent clone from flutter/devtools, and running that command from the `packages/flutter_app/`directory?

**Comment by devoncarew** [comment]
That exception indicates that somehow the vm service field in that file(FlutterVmService.httpAddress (package:flutter_tools/src/vmservice.dart:398:45)) is null. I'd update flutter to the latest. Does this repro w/ any flutter web app (like the hello world one)?

If you can't resolve the issue, this is best moved over to the flutter/flutter repo - this looks like an issues with flutter_tools.

**Comment by bl4ckck** [comment]
sorry for late respond. I've resolved this issue, I running devtools cli using this command
`flutter pub global run devtools `
but if I run devtools like my question, it still got errors.

**Comment by kenzieschmoll** [comment]
closing as fixed.
