### ISSUE TITLE
Timeline offline imports broken

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2004]

**Comment by kenzieschmoll** [comment]
I have a PR that fixes the break but now this error is being thrown:
```
Error: Assertion failed: file:///Users/kenzieschmoll/develop/flutter/packages/flutter/lib/src/widgets/navigator.dart:3150:12
!_debugLocked
is not true
    at Object.throw_ [as throw] (http://localhost:54080/dart_sdk.js:4462:11)
    at Object.assertFailed (http://localhost:54080/dart_sdk.js:4411:15)
    at navigator$.NavigatorState.new.[_routeNamed] (http://localhost:54080/packages/flutter/src/widgets/widget_span.dart.lib.js:18575:49)
    at navigator$.NavigatorState.new.pushNamed (http://localhost:54080/packages/flutter/src/widgets/widget_span.dart.lib.js:18606:57)
    at Function.pushNamed (http://localhost:54080/packages/flutter/src/widgets/widget_span.dart.lib.js:17550:47)
    at scaffold$.DevToolsScaffoldState.new.[_pushSnapshotScreenForImport] (http://localhost:54080/packages/devtools_app/src/logging/vm_service_logger.dart.lib.js:79665:29)
    at import_export.ImportController.new.importData (http://localhost:54080/packages/devtools_app/src/logging/vm_service_logger.dart.lib.js:78460:42)
    at http://localhost:54080/packages/devtools_app/src/logging/vm_service_logger.dart.lib.js:78661:18
    at Object._checkAndCall (http://localhost:54080/dart_sdk.js:4672:16)
    at Object.dcall (http://localhost:54080/dart_sdk.js:4677:17)
    at FileReader.<anonymous> (http://localhost:54080/dart_sdk.js:104619:21)Error: Assertion failed: file:///Users/kenzieschmoll/develop/flutter/packages/flutter/lib/src/widgets/navigator.dart:3150:12

```

**Comment by kenzieschmoll** [comment]
Tracking the navigator error separately https://github.com/flutter/devtools/issues/2021
