### ISSUE TITLE
"method not found: 'firstWhere$2$orElse' on null" running tests on Dart SDK v2.1 stable

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#204]
Doesn't seem to happen on Travis, but locally if I run:

```
WEBDEV_RELEASE=true pub run test --reporter expanded --exclude-tags useFlutterSdk
```

Then I get 3 failed tests:

```
00:43 +7 -1: test/integration_tests/integration_test.dart: integration debugging lists scripts [E]
  Expected: non-empty
    Actual: []
  
  package:test_api                           expect
  test/integration_tests/debugger.dart 38:5  debuggingTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                 _AsyncAwaitCompleter.completeError
  test/integration_tests/debugger.dart       debuggingTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                 _asyncThenWrapperHelper
  test/integration_tests/debugger.dart       debuggingTests.<fn>
  
00:43 +7 -1: test/integration_tests/integration_test.dart: integration debugging breakpoints, variables, resume
chrome • console:log • [{"event":"app.inited"}]
chrome • console:log • [{"id":1}]
chrome • console:log • [{"id":2,"result":"debugger"}]
chrome • console:log • [{"id":3,"result":[]}]
chrome • console:log • [{"id":4,"error":{"message":"NoSuchMethodError: method not found: 'firstWhere$2$orElse' on null","stackTrace":"TypeError: Cannot read property 'firstWhere$2$orElse' of null\n    at Object.J.firstWhere$2$orElse$ax (http://localhost:8080/main.dart.js:60336:41)\n    at http://localhost:8080/main.dart.js:37010:25\n    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)\n    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)\n    at Object.dart._asyncStartSync (http://localhost:8080/main.dart.js:9232:20)\n    at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$body$DebuggerState (http://localhost:8080/main.dart.js:37022:18)\n    at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$2 (http://localhost:8080/main.dart.js:36997:21)\n    at http://localhost:8080/main.dart.js:44495:143\n    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)\n    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)"}}]
00:45 +7 -2: test/integration_tests/integration_test.dart: integration debugging breakpoints, variables, resume [E]
  NoSuchMethodError: method not found: 'firstWhere$2$orElse' on null
  TypeError: Cannot read property 'firstWhere$2$orElse' of null
      at Object.J.firstWhere$2$orElse$ax (http://localhost:8080/main.dart.js:60336:41)
      at http://localhost:8080/main.dart.js:37010:25
      at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)
      at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)
      at Object.dart._asyncStartSync (http://localhost:8080/main.dart.js:9232:20)
      at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$body$DebuggerState (http://localhost:8080/main.dart.js:37022:18)
      at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$2 (http://localhost:8080/main.dart.js:36997:21)
      at http://localhost:8080/main.dart.js:44495:143
      at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)
      at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)
  dart:async                                      _Completer.completeError
  test/integration_tests/integration.dart 215:19  BrowserTabInstance._handleBrowserMessage
  test/integration_tests/integration.dart 131:15  new BrowserTabInstance.<fn>
  ===== asynchronous gap ===========================
  dart:async                                      _ForwardingStream.listen
  test/integration_tests/integration.dart 122:10  new BrowserTabInstance
  test/integration_tests/integration.dart 110:12  BrowserManager.createNewTab
  ===== asynchronous gap ===========================
  dart:async                                      _asyncThenWrapperHelper
  test/integration_tests/integration.dart         BrowserManager.createNewTab
  test/integration_tests/debugger.dart 15:40      debuggingTests.<fn>
  
00:45 +7 -2: test/integration_tests/integration_test.dart: integration debugging stepping, async step, async frames
chrome • console:log • [{"event":"app.inited"}]
chrome • console:log • [{"id":1}]
chrome • console:log • [{"id":2,"result":"debugger"}]
chrome • console:log • [{"id":3,"result":[]}]
chrome • console:log • [{"id":4,"error":{"message":"NoSuchMethodError: method not found: 'firstWhere$2$orElse' on null","stackTrace":"TypeError: Cannot read property 'firstWhere$2$orElse' of null\n    at Object.J.firstWhere$2$orElse$ax (http://localhost:8080/main.dart.js:60336:41)\n    at http://localhost:8080/main.dart.js:37010:25\n    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)\n    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)\n    at Object.dart._asyncStartSync (http://localhost:8080/main.dart.js:9232:20)\n    at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$body$DebuggerState (http://localhost:8080/main.dart.js:37022:18)\n    at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$2 (http://localhost:8080/main.dart.js:36997:21)\n    at http://localhost:8080/main.dart.js:44495:143\n    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)\n    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)"}}]
00:48 +7 -3: test/integration_tests/integration_test.dart: integration debugging stepping, async step, async frames [E]
  NoSuchMethodError: method not found: 'firstWhere$2$orElse' on null
  TypeError: Cannot read property 'firstWhere$2$orElse' of null
      at Object.J.firstWhere$2$orElse$ax (http://localhost:8080/main.dart.js:60336:41)
      at http://localhost:8080/main.dart.js:37010:25
      at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)
      at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)
      at Object.dart._asyncStartSync (http://localhost:8080/main.dart.js:9232:20)
      at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$body$DebuggerState (http://localhost:8080/main.dart.js:37022:18)
      at DebuggerState.dart.DebuggerState.addBreakpointByPathFragment$2 (http://localhost:8080/main.dart.js:36997:21)
      at http://localhost:8080/main.dart.js:44495:143
      at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:9269:15)
      at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:9824:14)
  dart:async                                      _Completer.completeError
  test/integration_tests/integration.dart 215:19  BrowserTabInstance._handleBrowserMessage
  test/integration_tests/integration.dart 131:15  new BrowserTabInstance.<fn>
  ===== asynchronous gap ===========================
  dart:async                                      _ForwardingStream.listen
  test/integration_tests/integration.dart 122:10  new BrowserTabInstance
  test/integration_tests/integration.dart 110:12  BrowserManager.createNewTab
  ===== asynchronous gap ===========================
  dart:async                                      _asyncThenWrapperHelper
  test/integration_tests/integration.dart         BrowserManager.createNewTab
  test/integration_tests/debugger.dart 15:40      debuggingTests.<fn>
  
00:48 +7 -3: test/integration_tests/integration_test.dart: integration debugging break on exceptions
```

**Comment by DanTup** [comment]
Ok, seems like this is just version related:

// passes with a recent nightly
WEBDEV_RELEASE=true /Users/dantup/Dev/dart-sdk/nightly-2019-01-13/bin/pub run test --reporter expanded --exclude-tags useFlutterSdk

// fails with v2.1 stable
WEBDEV_RELEASE=true pub run test --reporter expanded --exclude-tags useFlutterSdk

@devoncarew I presume this is probably expected (maybe we're using something that wasn't in v2.1 stable?), I guess in the editors we should gate launching this behind a Dart/Flutter version check?

**Comment by devoncarew** [comment]
> I presume this is probably expected (maybe we're using something that wasn't in v2.1 stable?)

I'm not aware of anything here. It's worth investigating, or at least opening an issue for.

We should increase our bot coverage to handle both the last dev release and the latest stable. I think that's a one line change in the .travis.yaml file :)

**Comment by DanTup** [comment]
Ok, if we don't know of anything new we need, I'll do some investigation + add to bots.

**Comment by DanTup** [comment]
Running locally in the browser (by using ` pub global run webdev serve --release`) I can hit a similar issue by trying to add a breakpoint in the debugger:

```
Error: NoSuchMethodError: method not found: 'call'
Receiver: Closure 'JsEventListener_stream__closure'
Arguments: [Instance of 'JsObject<>', 7, "CodeMirror-linenumbers", Instance of 'MouseEvent']
    at Object.dart.wrapException (main.dart.js:5096)
    at JsEventListener_stream__closure.dart.Object.noSuchMethod$1 (main.dart.js:20666)
    at Object.J.noSuchMethod$1$ (main.dart.js:60417)
    at Object.dart.Primitives_functionNoSuchMethod (main.dart.js:4895)
    at Object.dart.Primitives__genericApplyFunctionWithPositionalArguments (main.dart.js:4941)
    at Object.dart.Primitives_applyFunctionWithPositionalArguments (main.dart.js:4930)
    at Object.dart.Primitives_applyFunction (main.dart.js:4901)
    at Object.dart.Function__apply1 (main.dart.js:18809)
    at Object.dart.Function_apply (main.dart.js:18803)
    at dart._callDartFunction (main.dart.js:31602)
```

I think it's related to this code:

```dart
codeMirror.onGutterClick.listen((int line) {
```

I've tried a bit of blind stabbing but not got anywhere yet. I wonder if there needs to be an `allowInterop` or something somewhere (I've tried adding in a few places but no joy).

@devoncarew I'll come back to this, but if you have any ideas in the meantime, lmk!

**Comment by devoncarew** [comment]
allowInterop, or perhaps the wrong arity of parameters? Looks related to the debugger code in any case; I can take a look in the next few days.

**Comment by devoncarew** [comment]
W/ the codemirror wrapper, you call methods directly via js interop - you don't have to use the provided dart bindings. If we do find an issue with the dart wrapper, we can push the fix to the library and publish a new version.

**Comment by devoncarew** [comment]
Looking into this, the exceptions at the top of the issue are likely separate from the debugger gutter issue. For the debugger gutter issue, it does look like we're passing a callback into the codemirror APIs, and the callback is expecting the wrong arity of parameters. DDC is lenient about this; dart2js more strict.

@jmesserly, I think Jacob said you were aware of this, but FYI this may be the biggest thing we've hit in terms of getting an app developed against DDC to run under dart2js (the fact that DDC is more lenient in terms of allowing you to call a method with the wrong number of args). The other case where we hit this was https://github.com/flutter/devtools/issues/193#issuecomment-459302042.

**Comment by jmesserly** [comment]
@devoncarew good to know! Yeah I'll make sure https://github.com/dart-lang/sdk/issues/33134 is top priority to fix. After that, a few other common ones such as the way generic `List<T>` is checked for arrays coming from JS.

**Comment by devoncarew** [comment]
For the debugger exception: https://github.com/google/codemirror.dart/issues/85

**Comment by devoncarew** [comment]
@jmesserly - awesome, thanks!

**Comment by devoncarew** [comment]
@DanTup - I think the only part of this bug is the issues running the tests when the app is compiled with the stable sdk version of dart2js? If we just plan to use the dev sdk to compile for now (for testing and deployment), perhaps we can close this issue?

**Comment by DanTup** [comment]
Yeah, I think so - though I am kinda curious why it fails in stable and works in dev if we think there are actual issues in the code (wrong number of args) 🤔
