### ISSUE TITLE
Running DevTools sometimes will throw an exception in the Timeline at startup.

### ISSUE THREAD

**Issue by terrylucas** [flutter/devtools#2102]
Timeline page hasn't been selected and happens on startup w/ user interaction (switch to another page other than Timeline e.g., debugger, memory, etc).

```
Launching lib/main.dart on Linux in debug mode...
GLFW error 65544: X11: RandR gamma ramp support seems broken
flutter: DevTools version 0.2.6-dev.2.
Connecting to VM Service at ws://127.0.0.1:40451/ArG4nsLZslw=/ws
flutter: [WARNING]: Id collision on id 14
flutter: [WARNING]: Id collision on id 14
flutter: [WARNING]: Id collision on id 17
flutter: [WARNING]: Id collision on id 17
flutter: [WARNING]: Id collision on id 17
flutter: [WARNING]: Id collision on id 14
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:devtools_app/src/timeline/timeline_model.dart': Failed assertion: line 934 pos 7: 'asyncId == eventWrapper.event.id': asyncId = 31, but endEventId = 2f
[38;5;244m#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:40:39)[39;49m
[38;5;244m#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)[39;49m
[38;5;248m#2      AsyncTimelineEvent.endAsyncEvent[39;49m
[38;5;248m#3      AsyncTimelineEvent.endAsyncEvent[39;49m
[38;5;248m#4      TimelineProcessor._endAsyncEvent[39;49m
[38;5;248m#5      TimelineProcessor._processBatch[39;49m
[38;5;248m#6      TimelineProcessor.processTimeline[39;49m
[38;5;244m#7      _rootRunUnary  (dart:async/zone.dart:1198:47)[39;49m
[38;5;244m#8      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)[39;49m
[38;5;244m#9      _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244m#10     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244m#11     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244m#12     Future._completeWithValue  (dart:async/future_impl.dart:529:5)[39;49m
[38;5;244m#13     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)[39;49m
[38;5;244m#14     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)[39;49m
#15     delayForBatchProcessing (package:devtools_app/src/utils.dart)
[38;5;244m#16     _rootRunUnary  (dart:async/zone.dart:1198:47)[39;49m
[38;5;244m#17     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)[39;49m
[38;5;244m#18     _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)[39;49m
[38;5;244m#19     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)[39;49m
[38;5;244m#20     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)[39;49m
[38;5;244m#21     Future._complete  (dart:async/future_impl.dart:519:7)[39;49m
[38;5;244m#22     new Future.delayed.<anonymous closure>  (dart:async/future.dart:321:16)[39;49m
[38;5;244m#23     _rootRun  (dart:async/zone.dart:1182:47)[39;49m
[38;5;244m#24     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#25     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)[39;49m
[38;5;244m#26     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)[39;49m
[38;5;244m#27     _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#28     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#29     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)[39;49m
[38;5;244m#30     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)[39;49m
[38;5;244m#31     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)[39;49m
[38;5;244m#32     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)[39;49m
[38;5;244m#33     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m
```

**Comment by kenzieschmoll** [comment]
What version of Flutter are you on? How can I run the Flutter app you are seeing this with?
