### ISSUE TITLE
Unhandled exception for unknown arguments

### ISSUE THREAD

**Issue by Izzur** [flutter/devtools#2126]
When I run `flutter pub global run devtools --foobar`  
These unknown arguments throw an exception

```
> flutter pub global run devtools --foobar
Unhandled exception:
FormatException: Could not find an option named "foobar".
#0      Parser.validate (package:args/src/parser.dart:290:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:279:7)
#2      Parser.parse (package:args/src/parser.dart:88:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:326:42)
#4      serveDevToolsWithArgs (package:devtools_server/src/server.dart:137:26)
#5      main (file:///Users/izzur/Library/Flutter/.pub-cache/hosted/pub.dartlang.org/devtools-0.8.0/bin/devtools.dart:9:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

Probably from this [line of code](https://github.com/flutter/devtools/blob/75552ad80ea54c3a4b7cdfc11c8061dd946d19f8/packages/devtools_server/lib/src/server.dart#L137)

**Comment by elliette** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
