### ISSUE TITLE
Error in mp_chart when running locally in Chrome

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#2425]
I'm afraid I have no idea how I hit this, but I was moving between tabs and clicking Back in DevTools (running a dev build locally from VS Code) testing routing changes, and I hit this:

<img width="1163" alt="Screenshot 2020-10-12 at 18 46 52" src="https://user-images.githubusercontent.com/1078012/95776025-6b16b500-0cbb-11eb-9441-8263239303bd.png">

I don't know if the issue is in MP Charts or DevTools, but it looks like it expected a double and get an int (once 2500000000, and once 1602524781000), so this code failed to get the part after the decimal point. The full stack was:

```
"Error: RangeError (index): Index out of range: index should be less than 1: 1
    at Object.throw_ [as throw] (http://localhost:50738/dart_sdk.js:4332:11)
    at Array.[dartx._get] (http://localhost:50738/dart_sdk.js:15231:21)
    at Function.nextUp (http://localhost:50738/packages/mp_chart/mp/core/marker/radar_chart_marker.dart.lib.js:11050:57)
    at y_axis_renderer.YAxisRenderer.new.computeAxisValues (http://localhost:50738/packages/mp_chart/mp/core/marker/radar_chart_marker.dart.lib.js:1179:57)
    at y_axis_renderer.YAxisRenderer.new.computeAxis (http://localhost:50738/packages/mp_chart/mp/core/marker/radar_chart_marker.dart.lib.js:1135:12)
    at line_chart_painter.LineChartPainter.new.compute (http://localhost:50738/packages/mp_chart/mp/core/marker/radar_chart_marker.dart.lib.js:7536:35)
    at line_chart_painter.LineChartPainter.new.onPaint (http://localhost:50738/packages/mp_chart/mp/core/marker/radar_chart_marker.dart.lib.js:7405:14)
    at line_chart_painter.LineChartPainter.new.paint (http://localhost:50738/packages/mp_chart/mp/core/marker/radar_chart_marker.dart.lib.js:3633:14)
    at custom_paint.RenderCustomPaint.new.[_paintWithPainter] (http://localhost:50738/packages/flutter/src/rendering/custom_paint.dart.lib.js:327:15)
    at custom_paint.RenderCustomPaint.new.paint (http://localhost:50738/packages/flutter/src/rendering/custom_paint.dart.lib.js:344:32)
    at custom_paint.RenderCustomPaint.new.[_paintWithContext] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:3633:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6334:33)
    at proxy_box.RenderPointerListener.new.paint (http://localhost:50738/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:41)
    at proxy_box.RenderPointerListener.new.[_paintWithContext] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:3633:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6334:33)
    at proxy_box.RenderSemanticsGestureHandler.new.paint (http://localhost:50738/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:41)
    at proxy_box.RenderSemanticsGestureHandler.new.[_paintWithContext] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:3633:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6334:33)
    at proxy_box.RenderConstrainedBox.new.paint (http://localhost:50738/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:41)
    at proxy_box.RenderConstrainedBox.new.[_paintWithContext] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:3633:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6334:33)
    at stack.RenderStack.new.defaultPaint (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:8731:19)
    at stack.RenderStack.new.paintStack (http://localhost:50738/packages/flutter/src/rendering/stack.dart.lib.js:672:12)
    at stack.RenderStack.new.paint (http://localhost:50738/packages/flutter/src/rendering/stack.dart.lib.js:680:14)
    at stack.RenderStack.new.[_paintWithContext] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:3633:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6334:33)
    at proxy_box.RenderRepaintBoundary.new.paint (http://localhost:50738/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:41)
    at proxy_box.RenderRepaintBoundary.new.[_paintWithContext] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:3633:14)
    at Function._repaintCompositedChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6307:31)
    at Function.repaintCompositedChild (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6278:31)
    at object$.PipelineOwner.new.flushPaint (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6840:39)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6053:26)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:50738/packages/flutter/src/widgets/widget_span.dart.lib.js:49769:15)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:50738/packages/flutter/src/rendering/layer.dart.lib.js:6015:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:50738/packages/flutter/src/scheduler/binding.dart.lib.js:759:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:50738/packages/flutter/src/scheduler/binding.dart.lib.js:727:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:50738/packages/flutter/src/scheduler/binding.dart.lib.js:682:12)
    at Object._invoke (http://localhost:50738/dart_sdk.js:175979:7)
    at _engine.EngineWindow.new.invokeOnDrawFrame (http://localhost:50738/dart_sdk.js:171829:15)
    at http://localhost:50738/dart_sdk.js:172413:28"
```

**Comment by DanTup** [comment]
Oops - there's a try/catch around this, but I had enabled catch-on-all-exceptions while debugging something else 🙈
