### ISSUE TITLE
Assertion failure from lib/src/utils.dart:505:14 (TimeRange.start being set to null)

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#2430]
```
Error: Assertion failed: file:///Users/devoncarew/projects/flutter/devtools/packages/devtools_app/lib/src/utils.dart:505:14
_start == null
is not true
    at Object.throw_ [as throw] (http://localhost:9090/dart_sdk.js:4339:11)
    at Object.assertFailed (http://localhost:9090/dart_sdk.js:4282:15)
    at utils$2.TimeRange.new.set start [as start] (http://localhost:9090/packages/devtools_app/src/ui/gtags.dart.lib.js:105938:43)
    at http://localhost:9090/packages/devtools_app/src/ui/gtags.dart.lib.js:66087:24
    at timeline_processor.TimelineProcessor.new.processTimeline (http://localhost:9090/packages/devtools_app/src/ui/gtags.dart.lib.js:66090:13)
    at processTimeline.next (<anonymous>)
    at http://localhost:9090/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:9090/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:9090/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:9090/dart_sdk.js:33054:49)
    at Function._propagateToListeners (http://localhost:9090/dart_sdk.js:33092:17)
    at _Future.new.[_complete] (http://localhost:9090/dart_sdk.js:32926:25)
    at http://localhost:9090/dart_sdk.js:32073:30
    at internalCallback (http://localhost:9090/dart_sdk.js:23835:11)
Error: Assertion failed: file:///Users/devoncarew/projects/flutter/devtools/packages/devtools_app/lib/src/utils.dart:505:14
_start == null
is not true
    at Object.throw_ [as throw] (http://localhost:9090/dart_sdk.js:4339:11)
    at Object.assertFailed (http://localhost:9090/dart_sdk.js:4282:15)
    at utils$2.TimeRange.new.set start [as start] (http://localhost:9090/packages/devtools_app/src/ui/gtags.dart.lib.js:105938:43)
    at http://localhost:9090/packages/devtools_app/src/ui/gtags.dart.lib.js:66087:24
    at timeline_processor.TimelineProcessor.new.processTimeline (http://localhost:9090/packages/devtools_app/src/ui/gtags.dart.lib.js:66090:13)
    at processTimeline.next (<anonymous>)
    at http://localhost:9090/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:9090/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:9090/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:9090/dart_sdk.js:33054:49)
    at Function._propagateToListeners (http://localhost:9090/dart_sdk.js:33092:17)
    at _Future.new.[_complete] (http://localhost:9090/dart_sdk.js:32926:25)
    at http://localhost:9090/dart_sdk.js:32073:30
    at internalCallback (http://localhost:9090/dart_sdk.js:23835:11)
```

**Comment by devoncarew** [comment]
cc @terrylucas; for some reason, I mostly see this in the flutter web version of devtools, and less (or never?) with the flutter desktop version

**Comment by elliette** [comment]
Closing since this is most likely now obsolete.
