### ISSUE TITLE
Unhandled Exception: Exception: Unsupported RPC: The DevTools Server is not available on Desktop

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#2451]
I see this exception at startup, using macos desktop as a target, when running in debug mode from IntelliJ:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Unsupported RPC: The DevTools Server is not available on Desktop
#0      setActiveSurvey (package:devtools_app/src/config_specific/server/_server_stub.dart:25:3)
#1      SurveyService.activeSurvey (package:devtools_app/src/survey.dart:33:13)
<asynchronous suspension>
#2      SurveyService.maybeShowSurveyPrompt (package:devtools_app/src/survey.dart:43:20)
<asynchronous suspension>
```

**Comment by devoncarew** [comment]
It appears to fire every time Scaffold.didChangeDependencies() is called, which can happen often (on window resize? other times?).

**Comment by kenzieschmoll** [comment]
jacob has a CL out to fix https://github.com/flutter/devtools/pull/2448
