### ISSUE TITLE
Crash while parsing URI

### ISSUE THREAD

**Issue by filiph** [flutter/devtools#2543]
I have a flutter layout problem and I'm trying to inspect it using the Layout Explorer. The app is broken, with this:

```
RenderBox was not laid out: RenderFractionallySizedOverflowBox#f6e43 relayoutBoundary=up4 NEEDS-PAINT
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1785:12)
#3      Eval.<anonymous closure>.getLayoutExplorerNode.<anonymous closure> (:0:1752)
#4      InspectorSerializationDelegate.additionalNodeProperties (package:flutter/src/widgets/widget_inspector.dart:3058:52)
#5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1591:21)
#6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1606:6)
#7      _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4373:44)
#8      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1630:19)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#10     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#11     new List.from (dart:core-patch/array_patch.dart:38:29)
#12     new List.of (dart:core-patch/array_patch.dart:68:17)
#13     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1631:8)
#15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1599:23)
#16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1606:6)
#17     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:4373:44)
#18     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1443:18)
#19     Eval.<anonymous closure>.getLayoutExplorerNode (:0:605)
#20     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:547:32)
<asynchronous suspension>
#21     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart)
#22     _runExtension (dart:developer-patch/developer.dart:84:23)
```

When selecting the `Row` in the LayoutExplorer, it throws the following exception:

```
FormatException: Invalid empty scheme (at character 1)
:
^
_Uri._fail (uri.dart:1628)
new _Uri.notSimple (uri.dart:1461)
Uri.parse (uri.dart:1022)
StackFrame.fromStackTraceLine (stack_frame.dart:228)
MappedIterator.moveNext (iterable.dart:392)
WhereTypeIterator.moveNext (iterable.dart:875)
new List.from (array_patch.dart:50)
new List.of (array_patch.dart:68)
Iterable.toList (iterable.dart:404)
StackFrame.fromStackString (stack_frame.dart:95)
StackFrame.fromStackTrace (stack_frame.dart:80)
FlutterErrorDetails.debugFillProperties (assertions.dart:664)
DiagnosticableNode.builder.<anonymous closure> (diagnostics.dart:2945)
DiagnosticableNode.builder (diagnostics.dart:2948)
_FlutterErrorDetailsNode.builder (assertions.dart:1198)
DiagnosticableNode.emptyBodyDescription (diagnostics.dart:2959)
DiagnosticsNode.toJsonMap.<anonymous closure> (diagnostics.dart:1577)
DiagnosticsNode.toJsonMap (diagnostics.dart:1606)
WidgetInspectorService._nodeToJson (widget_inspector.dart:1443)
WidgetInspectorService._reportError (widget_inspector.dart:921)
FlutterError.reportError (assertions.dart:1092)
BindingBase.registerServiceExtension.<anonymous closure> (binding.dart:557)
<asynchronous gap>
_runExtension (developer.dart:84)
```

I think the tool is trying to rethrow the exception but somehow fails on URI parsing.

<img width="1061" alt="Screen Shot 2020-12-09 at 12 17 02 PM" src="https://user-images.githubusercontent.com/919717/101682557-a06c2480-3a18-11eb-9c48-67463d59848a.png">

Flutter code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor: Color(0xFFCD282B),
        accentColor: Color(0xFF1D49EB),
        visualDensity: VisualDensity.adaptivePlatformDensity,
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          selectedItemColor: Color(0xFF1D49EB),
          backgroundColor: Color(0xffe8eafd),
        )
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Row(
            children: <Widget>[
              FractionallySizedBox(
                widthFactor: 0.3,
                child: Text(
                  'You have pushed the button this many times:',
                  textAlign: TextAlign.right,
                ),
              ),
              SizedBox(width: 16),
              Expanded(
                child: Text(
                  '$_counter',
                  style: Theme.of(context)
                      .textTheme
                      .headline1
                      .apply(color: Theme.of(context).primaryColor),
                ),
              ),
            ],
          ),
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: [
          BottomNavigationBarItem(
              icon: Icon(Icons.account_circle_rounded), label: 'Face'),
          BottomNavigationBarItem(
              icon: Icon(Icons.accessibility_new_rounded), label: 'Body'),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by elliette** [comment]
This issue looks like it occurred on an old version of DevTools. Are you still experiencing this issue with DevTools on the latest Flutter stable? If so, please reopen and we will take a look. Thanks.
