### ISSUE TITLE
Exception thrown by memory view

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2625]
repro steps
- open memory page, play around, click on event timeline a few times
- switch to another tab (performance view for example)
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#75eb3](dirty, state: _OverlayEntryWidgetState#fc518):
This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 

Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
The relevant error-causing widget was: 
  Navigator-[LabeledGlobalKey<NavigatorState>#2a590] file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/lib/src/routing.dart:90:12
: To inspect this widget in Flutter DevTools, visit: http://127.0.0.1:9102/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A61339%2FPCXVVDeRcos%3D%2F&inspectorRef=inspector-15
When the exception was thrown, this was the stack: 
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:1088:9)
#1      State.context (package:flutter/src/widgets/framework.dart:1094:6)
#2      MemoryBodyState.hoverRow (package:devtools_app/src/memory/memory_screen.dart:701:38)
#3      MemoryBodyState.displayVmDataInHover (package:devtools_app/src/memory/memory_screen.dart:969:19)
#4      MemoryBodyState.showHover.<anonymous closure> (package:devtools_app/src/memory/memory_screen.dart:1094:24)
...
====================================================================================================
```

**Comment by terrylucas** [comment]
I believe this is fixed in current build.  The overlay wasn't being properly disposed of when switching tabs.
