### ISSUE TITLE
widget_inspector.dart throwing exception 

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2951]
I don't have consistent repro steps for this, but we should be able to do something to fail gracefully. The fix will actually be in the flutter repo, not devtools @jacob314 
```
======== Exception caught by Flutter framework =====================================================
The following _CastError was thrown during a service extension callback for "ext.flutter.inspector.getRootWidgetSummaryTree":
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      WidgetInspectorService._registerObjectGroupServiceExtension.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:793:84)
#1      WidgetInspectorService._registerObjectGroupServiceExtension.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:792:17)
#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:597:32)
<asynchronous suspension>
====================================================================================================
```

**Comment by kenzieschmoll** [comment]
This issue was reported quite a while ago (2021) and is a a framework-level exception. Since then, there have been numerous updates to both the Flutter framework and DevTools, so closing as obsolete.
