### ISSUE TITLE
Performance page crashing profile mode app

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2955]
```
flutter: getSourceReport: (112) Service has disappeared
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: getIsolate: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1606:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2078:21)
#2      VmService.getIsolate (package:vm_service/src/vm_service.dart:1843:7)
#3      VmServiceWrapper.getIsolate (package:devtools_app/src/vm_service_wrapper.dart:369:49)
#4      VmServiceWrapper.isHttpTimelineLoggingAvailable (package:devtools_app/src/vm_service_wrapper.dart:466:35)
#5      VmServiceWrapper.httpEnableTimelineLogging (package:devtools_app/src/vm_service_wrapper.dart:483:18)
#6      HttpService.toggleHttpRequestLogging.<anonymous closure> (package:devtools_app/src/http/http_service.dart:15:47)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#8      VmServiceWrapper.forEachIsolate (package:devtools_app/src/vm_service_wrapper.dart:82:5)
<asynchronous suspension>
#9      HttpService.toggleHttpRequestLogging (package:devtools_app/src/http/http_service.dart:11:5)
<asynchronous suspension>
#10     PerformanceController.toggleHttpRequestLogging (package:devtools_app/src/performance/performance_controller.dart:452:5)
<asynchronous suspension>
#11     PerformanceController._initHelper (package:devtools_app/src/performance/performance_controller.dart:158:5)
<asynchronous suspension>
```
@bkonyi any idea why the getIsolate call would be failing in profile mode?

**Comment by kenzieschmoll** [comment]
we are getting the same error `Service has disappeared` from the call to `service.getSourceReport` so this is not specific to the http timeline logging call.

**Comment by bkonyi** [comment]
Looks like we're hitting this [`UNIMPLEMENTED` check in the VM](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service.cc#L933), most likely due to [this `false` return value](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service.cc#L3351). We don't ever return `false` from the service RPC handlers, so I'm just going to remove the boolean returns so we don't hit this again.

**Comment by kenzieschmoll** [comment]
Closing this with Ben's fix.
