### ISSUE TITLE
devtools --profile-memory functionality stopped working with 2.0

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/devtools#3037]
See for example: https://flutter-flutter-perf.skia.org/e/?begin=1613512266&end=1621281842&queries=test%3Dlinux_complex_layout_scroll_perf__devtools_memory&requestType=0

We have several integration tests that do `pub global run devtools ... --profile-memory=...`. We've found that these are no longer collecting any data. When running the test locally, I get the following exception:

```
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [  +14 ms] Unhandled exception:
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] Exception: There are no registered methods for service "_flutter.listViews"
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] #0      MemoryProfile.callService (package:devtools_server/src/memory_profile.dart:90:7)
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] #1      MemoryProfile.getFlutterViewId (package:devtools_server/src/memory_profile.dart:219:43)
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] #2      MemoryProfile.getRasterCacheMetrics (package:devtools_server/src/memory_profile.dart:249:26)
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] #3      MemoryProfile._fetchRasterCacheInfo (package:devtools_server/src/memory_profile.dart:210:28)
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] #4      MemoryProfile._pollMemory (package:devtools_server/src/memory_profile.dart:190:25)
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stderr: [        ] <asynchronous suspension>
[complex_layout_scroll_perf__devtools_memory] [STDOUT] stdout: [ +396 ms] 00:00 +0: scrolling performance test (setUpAll)
```

**Comment by kenzieschmoll** [comment]
@terrylucas

**Comment by zanderso** [comment]
Marking this as P2 since we have potentially been blind to regressions in the benchmarks that use this for the past several weeks.

**Comment by kenzieschmoll** [comment]
I attempted a workaround for this that retried the call to `_flutter.listViews` once per second for 20 seconds, and it still failed with the same exception "Exception: There are no registered methods for service "_flutter.listViews". Is it possible that we have selected the wrong isolate [here](https://github.com/flutter/devtools/blob/master/packages/devtools_server/lib/src/memory_profile.dart#L173)? @terrylucas

**Comment by kenzieschmoll** [comment]
@zanderso @jonahwilliams is `_flutter.listViews` still a valid extension?

**Comment by jonahwilliams** [comment]
Yes, its registered by the engine and isn't isolate specific - do you know where that error message is coming from? it could be incorrect validation from some other service

**Comment by jonahwilliams** [comment]
ahh here: https://github.com/flutter/devtools/blame/c9c84a2342127a34ab74c2cc95e5bdcddd0b2260/packages/devtools_server/lib/src/memory_profile.dart#L90

This isn't a service call - its not registered by the tool - its registered by the engine/vm itself

**Comment by kenzieschmoll** [comment]
Ah, looks like we need to use service.callServiceExtension instead of service.callMethod
