### ISSUE TITLE
Exception caught by Flutter framework with Dart DevTools

### ISSUE THREAD

**Issue by binajmen** [flutter/devtools#3063]
Hi,

I'm running into the following exception when trying to launch DevTools (widget inspector in that case) in VS code
```
════════ Exception caught by Flutter framework ═════════════════════════════════
The following _TypeError was thrown during a service extension callback for "ext.flutter.inspector.getRootWidgetSummaryTree":
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack
#0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
package:flutter/…/widgets/widget_inspector.dart:1
#1      _Location.toJsonMap
package:flutter/…/widgets/widget_inspector.dart:2844
#2      _Location.toJsonMap.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:2853
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
...
════════════════════════════════════════════════════════════════════════════════
```

I recently added Firebase (which led me to mess in the `ios/` folder) but I doubt this is the reason.

**Comment by binajmen** [comment]
As it was a recent (and close to empty) project, I createed a new project and incrementally added the features already developed. No more exceptions.. Weird. I'll keep my old project in case I can provide further information to debug/understand the above exception.
