### ISSUE TITLE
Provider throwing exception when connected to flutter web app

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3069]
repro steps:
- run flutter gallery on the web
- connect it to devtools
- click on the "Reply" sample app within gallery
- navigate to the provider page and try to expand one of the properties

@rrousselGit 

More stack frames from dwds @grouma @annagrin @nshahan
```
flutter: [ERROR]: Provider AutoDisposeFutureProvider<InstanceDetails>#00048(from: Instance of 'AutoDisposeFutureProviderFamily<InstanceDetails, InstancePath>', argument: InstancePath.fromProviderId(providerId: 0, pathToProperty: [PathToProperty.objectProperty(name: starredEmailIds, ownerUri: package:gallery/studies/reply/model/email_store.dart, ownerName: EmailStore), PathToProperty.objectProperty(name: _map, ownerUri: dart:collection, ownerName: _IdentityHashSet<int>)])) failed with "getObject: (-32603) getObject: Unsupported operation: unknown library: null
#0      ClassHelper.forObjectId (package:dwds/src/debugging/classes.dart:66:7)
#1      AppInspector.getObject (package:dwds/src/debugging/inspector.dart:334:37)
<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1378:22)
<asynchronous suspension>
"
flutter: #0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1606:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2078:21)
#2      VmService.getObject (package:vm_service/src/vm_service.dart:1868:7)
#3      VmServiceWrapper.getObject (package:devtools_app/src/vm_service_wrapper.dart:396:48)
#4      EvalOnDartLibrary.getObjHelper.<anonymous closure> (package:devtools_app/src/eval_on_dart_library.dart:524:37)
#5      EvalOnDartLibrary.getObjHelper.<anonymous closure> (package:devtools_app/src/eval_on_dart_library.dart:523:35)
#6      EvalOnDartLibrary.addRequest (package:devtools_app/src/eval_on_dart_library.dart:467:21)
#7      EvalOnDartLibrary.getObjHelper (package:devtools_app/src/eval_on_dart_library.dart:523:12)
#8      EvalOnDartLibrary.getClass (package:devtools_app/src/eval_on_dart_library.dart:219:12)
#9      rawInstanceProvider.<anonymous closure> (package:devtools_app/src/provider/instance_viewer/instance_providers.dart:362:40)
<asynchronous suspension>
#10     _FutureProviderStateMixin.valueChanged.<anonymous closure> (package:riverpod/src/future_provider.dart)
<asynchronous suspension>
```

**Comment by grouma** [comment]
What version of Flutter?

I don't think we have done a roll of dependencies recently but this may be related to https://github.com/dart-lang/webdev/pull/1326

**Comment by kenzieschmoll** [comment]
I ran the flutter gallery app with Flutter 2.3.0-13.0.pre.191

**Comment by kenzieschmoll** [comment]
Now that the Provider panel is a DevTools extension, I'm closing this issue in favor of https://github.com/rrousselGit/provider/issues/883.
