### ISSUE TITLE
ReachabilityError: `null` encountered as case in a switch expression with a non-nullable enum type

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#3097]
This was from DevTools version 2.3.2, when connecting to a copy of the analysis server (which might have been running as an app-jit snapshot).

```
ReachabilityError: `null` encountered as case in a switch expression with a non-nullable enum type.
main.dart.js:10123     at Object.wrapException (http://127.0.0.1:9100/main.dart.js:7509:17)
main.dart.js:10123     at FocusManager._handleRawKeyEvent$1 (http://127.0.0.1:9100/main.dart.js:202315:25)
main.dart.js:10123     at Object.eval (eval at Closure_forwardCallTo (http://127.0.0.1:9100/main.dart.js:7873:14), <anonymous>:3:40)
main.dart.js:10123     at http://127.0.0.1:9100/main.dart.js:195636:104
main.dart.js:10123     at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:9100/main.dart.js:11783:15)
main.dart.js:10123     at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:9100/main.dart.js:87165:12)
main.dart.js:10123     at Object._asyncStartSync (http://127.0.0.1:9100/main.dart.js:11747:20)
main.dart.js:10123     at RawKeyboard._handleKeyEvent$1 (http://127.0.0.1:9100/main.dart.js:195645:16)
main.dart.js:10123     at Object.eval (eval at Closure_forwardCallTo (http://127.0.0.1:9100/main.dart.js:7873:14), <anonymous>:3:40)
main.dart.js:10123     at http://127.0.0.1:9100/main.dart.js:195331:56
```

**Comment by kenzieschmoll** [comment]
closing as obsolete since this looks like this was from pre-NNBD
