### ISSUE TITLE
Inspector throwing exception

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3176]
Error: RangeError (index): Index out of range: index must not be negative: -1
    at Object.throw_ [as throw] (http://localhost:58197/dart_sdk.js:5369:11)
    at Array.[dartx._get] (http://localhost:58197/dart_sdk.js:16264:21)
    at inspector_tree_flutter.InspectorTreeControllerFlutter.new.getCachedRow (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:80255:20)
    at inspector_tree_flutter._InspectorTreeState.new.[_computeTargetX] (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:80809:35)
    at inspector_tree_flutter._InspectorTreeState.new.scrollToRect (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:80835:48)
    at scrollToRect.next (<anonymous>)
    at runBody (http://localhost:58197/dart_sdk.js:39306:34)
    at Object._async [as async] (http://localhost:58197/dart_sdk.js:39337:7)
    at inspector_tree_flutter._InspectorTreeState.new.scrollToRect (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:80823:20)
    at inspector_tree_flutter.InspectorTreeControllerFlutter.new.scrollToRect (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:80623:16)
    at inspector_tree_flutter.InspectorTreeControllerFlutter.new.animateToTargets (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:80568:12)
    at inspector_controller.InspectorController.new.animateTo (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:86024:26)
    at inspector_controller.InspectorController.new.setSelectedNode (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:86039:12)
    at inspector_controller.InspectorController.new.refreshSelection (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:85882:12)
    at inspector_controller.InspectorController.new.recomputeTreeRoot (http://localhost:58197/packages/devtools_app/src/preferences.dart.lib.js:85836:16)
    at recomputeTreeRoot.next (<anonymous>)
    at http://localhost:58197/dart_sdk.js:39286:33
    at _RootZone.runUnary (http://localhost:58197/dart_sdk.js:39143:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:58197/dart_sdk.js:34105:29)
    at handleValueCallback (http://localhost:58197/dart_sdk.js:34665:49)
    at Function._propagateToListeners (http://localhost:58197/dart_sdk.js:34703:17)
    at Function._propagateToListeners (http://localhost:58197/dart_sdk.js:34611:27)
    at _Future.new.[_completeWithValue] (http://localhost:58197/dart_sdk.js:34545:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58197/dart_sdk.js:34568:35)
    at Object._microtaskLoop (http://localhost:58197/dart_sdk.js:39430:13)
    at _startMicrotaskLoop (http://localhost:58197/dart_sdk.js:39436:13)
    at http://localhost:58197/dart_sdk.js:34919:9

@jacob314

**Comment by elliette** [comment]
We are now using `safeGet` (https://github.com/flutter/devtools/blob/125ef5fdfeea1c553a49be28f828ecb10d914822/packages/devtools_app/lib/src/shared/primitives/utils.dart#L640) in the `.getCachedRow` method, so I don't think this error is possible now.
