### ISSUE TITLE
review history does not work

### ISSUE THREAD

**Issue by ristiisa** [flutter/devtools#3229]
After profile session is closed it is not possible to view previously recorded data. After pressing "Review History" button the screen is just blank.

![image](https://user-images.githubusercontent.com/514571/127739187-6a7fd0c6-5d86-48f2-9442-16ed86b6b39e.png)

<details>

```
main.dart.js:4087 WebSocketChannelException: WebSocket connection failed.

log @ main.dart.js:4087
(anonymous) @ main.dart.js:9376
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$2 @ main.dart.js:88565
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
handleError$1 @ main.dart.js:89305
call$0 @ main.dart.js:89658
_Future__propagateToListeners @ main.dart.js:35453
_completeError$2 @ main.dart.js:89477
call$0 @ main.dart.js:89582
_rootRun @ main.dart.js:35730
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:91160
_microtaskLoop @ main.dart.js:35512
_startMicrotaskLoop @ main.dart.js:35518
call$1 @ main.dart.js:88440
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
childList (async)
call$1 @ main.dart.js:88450
_scheduleAsyncCallback @ main.dart.js:35532
_rootScheduleMicrotask @ main.dart.js:35787
scheduleMicrotask$1 @ main.dart.js:91078
_asyncCompleteError$2 @ main.dart.js:89504
_completeError$2 @ main.dart.js:89274
completeError$2 @ main.dart.js:89250
completeError$1 @ main.dart.js:89253
call$1 @ main.dart.js:145295
_invokeErrorHandler @ main.dart.js:35244
_handleError$3 @ main.dart.js:90907
_handleError$2 @ main.dart.js:90853
eval @ VM1802:3
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
runBinaryGuarded$2$3 @ main.dart.js:90995
call$0 @ main.dart.js:90449
_sendError$2 @ main.dart.js:90347
_addError$2 @ main.dart.js:90288
_sendError$2 @ main.dart.js:90087
_addError$2 @ main.dart.js:90000
addError$2 @ main.dart.js:89970
eval @ VM1806:3
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
runBinaryGuarded$2$3 @ main.dart.js:90995
call$0 @ main.dart.js:90449
_sendError$2 @ main.dart.js:90347
_addError$2 @ main.dart.js:90288
_sendError$2 @ main.dart.js:90087
_addError$2 @ main.dart.js:90000
addError$2 @ main.dart.js:89970
_guarantee_channel$_addError$2 @ main.dart.js:237957
addError$2 @ main.dart.js:237949
addError$1 @ main.dart.js:237952
call$1 @ main.dart.js:244177
_rootRunUnary @ main.dart.js:35740
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_complete$1 @ main.dart.js:89464
_cancelAndValue @ main.dart.js:35686
call$1 @ main.dart.js:89852
call$1 @ main.dart.js:99416
_rootRunUnary @ main.dart.js:35746
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
runUnaryGuarded$1$2 @ main.dart.js:90985
call$1 @ main.dart.js:91166
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
error (async)
_addEventListener$3 @ main.dart.js:97498
addEventListener$3 @ main.dart.js:97485
addEventListener$3$x @ main.dart.js:24292
_tryResume$0 @ main.dart.js:99392
onData$1 @ main.dart.js:99366
get$first @ main.dart.js:89761
HtmlWebSocketChannel$1 @ main.dart.js:244158
HtmlWebSocketChannel$connect @ main.dart.js:2373
(anonymous) @ main.dart.js:46439
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
_connectWithWebSocket @ main.dart.js:46462
(anonymous) @ main.dart.js:145329
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
call$0 @ main.dart.js:145348
connect @ main.dart.js:46469
(anonymous) @ main.dart.js:9338
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
FrameworkCore_initVmService$body @ main.dart.js:9411
FrameworkCore_initVmService @ main.dart.js:9308
(anonymous) @ main.dart.js:117419
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
_attemptUrlConnection$0 @ main.dart.js:117429
call$0 @ main.dart.js:117458
notifyListeners$0 @ main.dart.js:156817
set$value @ main.dart.js:156915
vmServiceClosed$1$connectionState @ main.dart.js:145616
vmServiceClosed$0 @ main.dart.js:145620
call$1 @ main.dart.js:145932
_rootRunUnary @ main.dart.js:35740
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_completeWithValue$1 @ main.dart.js:89472
call$0 @ main.dart.js:89570
_rootRun @ main.dart.js:35730
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:91160
_microtaskLoop @ main.dart.js:35512
_startMicrotaskLoop @ main.dart.js:35518
call$1 @ main.dart.js:88440
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
childList (async)
call$1 @ main.dart.js:88450
_scheduleAsyncCallback @ main.dart.js:35532
_rootScheduleMicrotask @ main.dart.js:35787
scheduleMicrotask$1 @ main.dart.js:91078
_asyncCompleteWithValue$1 @ main.dart.js:89488
_asyncComplete$1 @ main.dart.js:89484
complete$1 @ main.dart.js:89268
complete$0 @ main.dart.js:89271
_onStreamDisconnected$0 @ main.dart.js:237999
call$0 @ main.dart.js:237922
_rootRun @ main.dart.js:35724
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:90463
_sendDone$0 @ main.dart.js:90360
_close$0 @ main.dart.js:90300
_sendDone$0 @ main.dart.js:90090
close$0 @ main.dart.js:89984
close$0 @ main.dart.js:237990
call$1 @ main.dart.js:244196
_rootRunUnary @ main.dart.js:35740
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_complete$1 @ main.dart.js:89464
_cancelAndValue @ main.dart.js:35686
call$1 @ main.dart.js:89852
call$1 @ main.dart.js:99416
_rootRunUnary @ main.dart.js:35746
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
runUnaryGuarded$1$2 @ main.dart.js:90985
call$1 @ main.dart.js:91166
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
Show 137 more frames
(index):86 HttpRequest api/getDevToolsEnabled failed status = null
window.console.warn @ (index):86
log @ main.dart.js:4082
logWarning @ main.dart.js:44950
(anonymous) @ main.dart.js:44553
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$1 @ main.dart.js:88559
runUnary$2$2 @ main.dart.js:91310
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_completeWithValue$1 @ main.dart.js:89472
complete$1 @ main.dart.js:88533
_asyncReturn @ main.dart.js:35122
(anonymous) @ main.dart.js:44493
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$2 @ main.dart.js:88565
runBinary$3$3 @ main.dart.js:91315
handleError$1 @ main.dart.js:89305
call$0 @ main.dart.js:89658
_Future__propagateToListeners @ main.dart.js:35453
_completeError$2 @ main.dart.js:89477
call$0 @ main.dart.js:89582
_microtaskLoop @ main.dart.js:35512
_startMicrotaskLoop @ main.dart.js:35518
call$1 @ main.dart.js:88440
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
childList (async)
call$1 @ main.dart.js:88450
_scheduleAsyncCallback @ main.dart.js:35532
_rootScheduleMicrotask @ main.dart.js:35787
scheduleMicrotask$1 @ main.dart.js:91331
_asyncCompleteError$2 @ main.dart.js:89504
_completeError$2 @ main.dart.js:89274
completeError$2 @ main.dart.js:89250
completeError$1 @ main.dart.js:89253
eval @ VM1659:3
call$1 @ main.dart.js:99410
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
error (async)
_addEventListener$3 @ main.dart.js:97498
addEventListener$3 @ main.dart.js:97485
addEventListener$3$x @ main.dart.js:24292
_tryResume$0 @ main.dart.js:99392
_EventStreamSubscription$ @ main.dart.js:57331
HttpRequest_request @ main.dart.js:57279
(anonymous) @ main.dart.js:44464
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
_request$body @ main.dart.js:44499
_request @ main.dart.js:44446
(anonymous) @ main.dart.js:44546
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
isAnalyticsEnabled0 @ main.dart.js:44565
(anonymous) @ main.dart.js:9559
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
isAnalyticsEnabled @ main.dart.js:9572
(anonymous) @ main.dart.js:10367
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
GTag_exception @ main.dart.js:10376
reportError @ main.dart.js:9609
_reportError @ main.dart.js:58000
call$2 @ main.dart.js:104823
runBinary$3$3 @ main.dart.js:91315
call$5 @ main.dart.js:91378
_processUncaughtError$3 @ main.dart.js:90948
handleUncaughtError$2 @ main.dart.js:91026
_Future__propagateToListeners @ main.dart.js:35406
_completeError$2 @ main.dart.js:89477
completeError$2 @ main.dart.js:88545
_asyncRethrow @ main.dart.js:35125
(anonymous) @ main.dart.js:129551
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$2 @ main.dart.js:88565
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
handleError$1 @ main.dart.js:89305
call$0 @ main.dart.js:89658
_Future__propagateToListeners @ main.dart.js:35453
_completeError$2 @ main.dart.js:89477
completeError$2 @ main.dart.js:88545
_asyncRethrow @ main.dart.js:35125
(anonymous) @ main.dart.js:239894
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$2 @ main.dart.js:88565
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
handleError$1 @ main.dart.js:89305
call$0 @ main.dart.js:89658
_Future__propagateToListeners @ main.dart.js:35453
_completeError$2 @ main.dart.js:89477
call$0 @ main.dart.js:89582
_rootRun @ main.dart.js:35730
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:91160
_microtaskLoop @ main.dart.js:35512
_startMicrotaskLoop @ main.dart.js:35518
call$1 @ main.dart.js:88440
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
childList (async)
call$1 @ main.dart.js:88450
_scheduleAsyncCallback @ main.dart.js:35532
_rootScheduleMicrotask @ main.dart.js:35787
scheduleMicrotask$1 @ main.dart.js:91078
_asyncCompleteWithValue$1 @ main.dart.js:89488
_asyncComplete$1 @ main.dart.js:89484
complete$1 @ main.dart.js:89268
complete$0 @ main.dart.js:89271
_onStreamDisconnected$0 @ main.dart.js:237999
call$0 @ main.dart.js:237922
_rootRun @ main.dart.js:35724
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:90463
_sendDone$0 @ main.dart.js:90360
_close$0 @ main.dart.js:90300
_sendDone$0 @ main.dart.js:90090
close$0 @ main.dart.js:89984
close$0 @ main.dart.js:237990
call$1 @ main.dart.js:244196
_rootRunUnary @ main.dart.js:35740
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_complete$1 @ main.dart.js:89464
_cancelAndValue @ main.dart.js:35686
call$1 @ main.dart.js:89852
call$1 @ main.dart.js:99416
_rootRunUnary @ main.dart.js:35746
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
runUnaryGuarded$1$2 @ main.dart.js:90985
call$1 @ main.dart.js:91166
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
Show 110 more frames
main.dart.js:57283 POST http://127.0.0.1:9105/api/getDevToolsEnabled net::ERR_CONNECTION_REFUSED
HttpRequest_request @ main.dart.js:57283
(anonymous) @ main.dart.js:44464
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
_request$body @ main.dart.js:44499
_request @ main.dart.js:44446
(anonymous) @ main.dart.js:44546
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
isAnalyticsEnabled0 @ main.dart.js:44565
(anonymous) @ main.dart.js:9559
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
isAnalyticsEnabled @ main.dart.js:9572
(anonymous) @ main.dart.js:10367
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
GTag_exception @ main.dart.js:10376
reportError @ main.dart.js:9609
_reportError @ main.dart.js:58000
call$2 @ main.dart.js:104823
runBinary$3$3 @ main.dart.js:91315
call$5 @ main.dart.js:91378
_processUncaughtError$3 @ main.dart.js:90948
handleUncaughtError$2 @ main.dart.js:91026
_Future__propagateToListeners @ main.dart.js:35406
_completeError$2 @ main.dart.js:89477
completeError$2 @ main.dart.js:88545
_asyncRethrow @ main.dart.js:35125
(anonymous) @ main.dart.js:129551
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$2 @ main.dart.js:88565
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
handleError$1 @ main.dart.js:89305
call$0 @ main.dart.js:89658
_Future__propagateToListeners @ main.dart.js:35453
_completeError$2 @ main.dart.js:89477
completeError$2 @ main.dart.js:88545
_asyncRethrow @ main.dart.js:35125
(anonymous) @ main.dart.js:239894
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$2 @ main.dart.js:88565
_rootRunBinary @ main.dart.js:35756
(anonymous) @ main.dart.js:245009
runBinary$3$3 @ main.dart.js:91049
handleError$1 @ main.dart.js:89305
call$0 @ main.dart.js:89658
_Future__propagateToListeners @ main.dart.js:35453
_completeError$2 @ main.dart.js:89477
call$0 @ main.dart.js:89582
_rootRun @ main.dart.js:35730
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:91160
_microtaskLoop @ main.dart.js:35512
_startMicrotaskLoop @ main.dart.js:35518
call$1 @ main.dart.js:88440
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
childList (async)
call$1 @ main.dart.js:88450
_scheduleAsyncCallback @ main.dart.js:35532
_rootScheduleMicrotask @ main.dart.js:35787
scheduleMicrotask$1 @ main.dart.js:91078
_asyncCompleteWithValue$1 @ main.dart.js:89488
_asyncComplete$1 @ main.dart.js:89484
complete$1 @ main.dart.js:89268
complete$0 @ main.dart.js:89271
_onStreamDisconnected$0 @ main.dart.js:237999
call$0 @ main.dart.js:237922
_rootRun @ main.dart.js:35724
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:90463
_sendDone$0 @ main.dart.js:90360
_close$0 @ main.dart.js:90300
_sendDone$0 @ main.dart.js:90090
close$0 @ main.dart.js:89984
close$0 @ main.dart.js:237990
call$1 @ main.dart.js:244196
_rootRunUnary @ main.dart.js:35740
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_complete$1 @ main.dart.js:89464
_cancelAndValue @ main.dart.js:35686
call$1 @ main.dart.js:89852
call$1 @ main.dart.js:99416
_rootRunUnary @ main.dart.js:35746
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
runUnaryGuarded$1$2 @ main.dart.js:90985
call$1 @ main.dart.js:91166
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
Show 75 more frames
main.dart.js:57281 POST http://127.0.0.1:9105/api/sse?sseClientId=37ef9e51-5627-4f4a-9c14-9b16c277097e&messageId=9 net::ERR_CONNECTION_REFUSED
HttpRequest_request @ main.dart.js:57281
(anonymous) @ main.dart.js:237252
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
_asyncStartSync @ main.dart.js:35114
call$0 @ main.dart.js:237285
(anonymous) @ main.dart.js:234436
(anonymous) @ main.dart.js:35150
call$2 @ main.dart.js:88571
call$1 @ main.dart.js:88559
runUnary$2$2 @ main.dart.js:91310
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_completeWithValue$1 @ main.dart.js:89472
call$0 @ main.dart.js:89570
_microtaskLoop @ main.dart.js:35512
_startMicrotaskLoop @ main.dart.js:35518
call$1 @ main.dart.js:88440
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
childList (async)
call$1 @ main.dart.js:88450
_scheduleAsyncCallback @ main.dart.js:35532
_rootScheduleMicrotask @ main.dart.js:35787
scheduleMicrotask$1 @ main.dart.js:91078
_asyncCompleteWithValue$1 @ main.dart.js:89488
_asyncComplete$1 @ main.dart.js:89484
complete$1 @ main.dart.js:89268
complete$0 @ main.dart.js:89271
_onStreamDisconnected$0 @ main.dart.js:237999
call$0 @ main.dart.js:237922
_rootRun @ main.dart.js:35724
(anonymous) @ main.dart.js:245003
run$1$1 @ main.dart.js:91039
runGuarded$1 @ main.dart.js:90975
call$0 @ main.dart.js:90463
_sendDone$0 @ main.dart.js:90360
_close$0 @ main.dart.js:90300
_sendDone$0 @ main.dart.js:90090
close$0 @ main.dart.js:89984
close$0 @ main.dart.js:237990
call$1 @ main.dart.js:244196
_rootRunUnary @ main.dart.js:35740
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
call$0 @ main.dart.js:89640
_Future__propagateToListeners @ main.dart.js:35451
_complete$1 @ main.dart.js:89464
_cancelAndValue @ main.dart.js:35686
call$1 @ main.dart.js:89852
call$1 @ main.dart.js:99416
_rootRunUnary @ main.dart.js:35746
(anonymous) @ main.dart.js:245006
runUnary$2$2 @ main.dart.js:91044
runUnaryGuarded$1$2 @ main.dart.js:90985
call$1 @ main.dart.js:91166
invokeClosure @ main.dart.js:20936
(anonymous) @ main.dart.js:20955
Show 27 more frames
main.dart.js:20733 Uncaught Bad state: Cannot add event after closing
    at Object.wrapException (http://127.0.0.1:9105/main.dart.js:20733:17)
    at _AsyncStreamController.addError$2 (http://127.0.0.1:9105/main.dart.js:89963:17)
    at _AsyncStreamController.addError$1 (http://127.0.0.1:9105/main.dart.js:89973:19)
    at SseClient__closure.call$0 (http://127.0.0.1:9105/main.dart.js:237213:30)
    at _TimerImpl_internalCallback.call$0 (http://127.0.0.1:9105/main.dart.js:88503:21)
    at invokeClosure (http://127.0.0.1:9105/main.dart.js:20934:26)
    at http://127.0.0.1:9105/main.dart.js:20955:18
```
</details> 

`Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-arm, locale en-GB)`
`Google Chrome 92.0.4515.107 (Official Build) (arm64)`

**Comment by kenzieschmoll** [comment]
this is resolved. History is available for any screen that supports loading offline data.
