### ISSUE TITLE
Memory screen throwing NoSuchMethodError

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3410]
```
flutter: [ERROR]: NoSuchMethodError: The method '/' was called on null.
Receiver: null
Tried calling: /(2884615.3846153845)

======== Exception caught by rendering library =====================================================
The following NoSuchMethodError was thrown during paint():
The method '/' was called on null.
Receiver: null
Tried calling: /(2884615.3846153845)

The relevant error-causing widget was: 
  CustomPaint CustomPaint:file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/lib/src/charts/chart.dart:115:22
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1      AxisScale.tickFromValue (package:devtools_app/src/charts/chart_trace.dart:404:14)
#2      ChartController.yPosition (package:devtools_app/src/charts/chart_controller.dart:443:41)
#3      ChartController.yPositionToYCanvasCoord (package:devtools_app/src/charts/chart_controller.dart:448:48)
#4      ChartPainter.paint.<anonymous closure> (package:devtools_app/src/charts/chart.dart:259:39)
#5      drawTranslate (package:devtools_app/src/charts/chart.dart:36:11)
#6      ChartPainter.paint (package:devtools_app/src/charts/chart.dart:252:15)
#7      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#8      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#20     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:341:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#25     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#26     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#27     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#28     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#29     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#33     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#37     _invoke (dart:ui/hooks.dart:150:10)
#38     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#39     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#02e31
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1470.0, h=150.0)
...  size: Size(1470.0, 150.0)
RenderObject: RenderCustomPaint#02e31
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1470.0, h=150.0)
  size: Size(1470.0, 150.0)
====================================================================================================
```

**Comment by polina-c** [comment]
we migrated to null safety, so it should not repeat
