### ISSUE TITLE
`NoSuchMethodError: The getter 'microsecondsSinceEpoch' was called on null.` 

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#3543]
This is currently the most common error from Dart DevTools while debugging Dart Web apps. It doesn't appear to be affecting the debugging functionality, but it is causing a lot of noise in our error tracking. 

```
XMLHttpRequest error.
ext.dwds.sendEvent: (-32000) 
Receiver: null
Tried calling: microsecondsSinceEpoch
#0 Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1 DateTime.difference (dart:core-patch/date_patch.dart:212:54)
#2 _processSendEvent (package:dwds/src/dwds_vm_client.dart:157:18)
#3 DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:107:7)
#4 DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:106:58)
#5 VmService._routeRequest (package:vm_service/src/vm_service.dart:2253:27)
#6 VmService._processRequest (package:vm_service/src/vm_service.dart:2223:25)
#7 VmService._processMessageStr (package:vm_service/src/vm_service.dart:2190:9)
#8 VmService._processMessage (package:vm_service/src/vm_service.dart:2148:7)
#9 _rootRunUnary (dart:async/zone.dart:1436:47)
#10 _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#11 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#12 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14 _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#15 _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#16 _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#17 _rootRunUnary (dart:async/zone.dart:1444:13)
#18 _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#19 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#20 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#21 _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#23 _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#24 StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#25 StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#26 _rootRun (dart:async/zone.dart:1420:47)
#27 _CustomZone.run (dart:async/zone.dart:1328:19)
#28 _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#29 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#30 StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#31 StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#32 _rootRun (dart:async/zone.dart:1428:13)
#33 _CustomZone.run (dart:async/zone.dart:1328:19)
#34 _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#35 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#36 _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#37 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#38 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#39 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

**Comment by kenzieschmoll** [comment]
This looks like a bug in dwds. Should this issue be moved there?

**Comment by elliette** [comment]
Good point, opened https://github.com/dart-lang/webdev/issues/1468 instead
