### ISSUE TITLE
../devtools-2.9.2/build" could not be found

### ISSUE THREAD

**Issue by Kristen-dev** [flutter/devtools#3551]
Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath
"/Users/life_dxy/.pub-cache/hosted/pub.flutter-io.cn/devtools-2.9.2/build" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:38:23)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:215:15)
<asynchronous suspension>
#3      serveDevToolsWithArgs (package:devtools_server/src/server.dart:73:10)
<asynchronous suspension>

**Comment by auaicn** [comment]
me for same issues...

**Comment by wuchuixu** [comment]
Me too

**Comment by auaicn** [comment]
" dart pub global activate devtools -v 2.8.0

worked for me !

**Comment by 18805699674** [comment]
> ```
> dart pub global activate devtools -v 2.8.0
> ```
> 
> worked for me !

Thank you
