### ISSUE TITLE
Button "Review History" does not work.

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#3756]
Steps to reporo:

1. Run DevTools on macos
2. Connect to an app
3. Kill the app to cause disconnect
4. Click button "Review History"

Expected: history of the application execution
Actual: empty screen

**Comment by polina-c** [comment]
Error at the moment of disconnect:

```
flutter: [ERROR]: 'package:devtools_app/src/inspector/inspector_tree_controller.dart': Failed assertion: line 710 pos 16: 'isSummaryTree == (inspectorTreeController == null)': is not true.

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building InspectorScreenBody(dirty, dependencies:
[_InheritedProviderScope<DebuggerController>], state: InspectorScreenBodyState#30e15):
'package:devtools_app/src/inspector/inspector_tree_controller.dart': Failed assertion: line 710 pos
16: 'isSummaryTree == (inspectorTreeController == null)': is not true.

The relevant error-causing widget was:
  InspectorScreenBody
  InspectorScreenBody:file:///Users/polinach/_/flutter/devtools/packages/devtools_app/lib/src/inspector/inspector_screen.dart:56:47

When the exception was thrown, this was the stack:
#2      new InspectorTree (package:devtools_app/src/inspector/inspector_tree_controller.dart:710:16)
#3      InspectorScreenBodyState.build (package:devtools_app/src/inspector/inspector_screen.dart:155:25)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (7 frames)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#18     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#19     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (13 frames)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#33     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (84 frames)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#120    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#121    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:20)
#122    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#123    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#124    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#125    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1997:59)
#126    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#127    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1997:14)
#128    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#129    RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
#130    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:205:12)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#132    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#133    _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#134    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#135    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#136    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#137    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#138    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#139    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#140    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#142    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#144    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#145    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#146    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#148    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#149    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#150    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#151    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#152    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#153    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#154    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#155    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#156    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#157    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#158    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#159    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#160    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#161    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#162    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#163    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#164    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#165    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#166    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#167    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#168    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#169    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#170    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#171    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#172    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#173    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#177    _invoke (dart:ui/hooks.dart:151:10)
#178    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#179    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: [ERROR]: NoSuchMethodError: The getter 'inspectorTree' was called on null.
Receiver: null
Tried calling: inspectorTree

Another exception was thrown: NoSuchMethodError: The getter 'inspectorTree' was called on null.


```

**Comment by kenzieschmoll** [comment]
This is fixed by https://github.com/flutter/devtools/pull/5509
