### ISSUE TITLE
Unable to connect DevTools to running Flutter app in Profile mode (NPE)

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#3760]
Using latest Flutter `master`, if I run a Flutter app in profile mode on a device with:

```
flutter run --profile
```

And then go to the URL in the output for DevTools:

```
The Flutter DevTools debugger and profiler on Mi A2 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:53027/SgwbTbAw7-k=/
```

It fails to connect with this error:

![Screenshot 2022-03-02 at 15 23 59](https://user-images.githubusercontent.com/1078012/156391980-592223a8-87b7-4128-a88d-fbaf50091536.png)

```
main.dart.js:63056 NoSuchMethodError: method not found: 'toString' on null
TypeError: Cannot read properties of null (reading 'toString')
    at EvalOnDartLibrary_eval__closure.call$1 (main.dart.js:147552:13)
    at Object._rootRunUnary (main.dart.js:10993:18)
    at StaticClosure.<anonymous> (main.dart.js:253397:16)
    at _CustomZone.runUnary$2$2 (main.dart.js:93458:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:92134:51)
    at Object._Future__propagateToListeners (main.dart.js:10704:93)
    at _Future._completeWithValue$1 (main.dart.js:91966:9)
    at _AsyncAwaitCompleter.complete$1 (main.dart.js:91043:14)
    at Object._asyncReturn (main.dart.js:10374:17)
    at main.dart.js:147146:24
```

**Comment by kenzieschmoll** [comment]
@polina-c
`.then((value) => value!)` was added as part of migrating this file to null safety. We should get rid of this then statement with the unconditional unwrap.
