### ISSUE TITLE
Setting flex factor in the layout explorer is broken

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3984]
Repro steps:
1. select a flex widget in the inspector
2. try to change the flex value to any number

The assertion that is failing is in the flutter framework: https://github.com/flutter/flutter/blob/078deb9230bec918dd5d815092a6c54966ffde6b/packages/flutter/lib/src/foundation/stack_frame.dart#L205

setFlexFactor is defined as part of the inspectorPolyFill script. @jacob314 do you know how to debug this? I tried adding prints and breakpoints inside the polyfill scripts (both in DevTools and the framework) but none of them were hit.

```
Attempted to call extension 'ext.flutter.inspector.structuredErrors', but no service with that name exists
[ERROR:flutter/runtime/dart_vm_initializer.cc(39)] Unhandled Exception: ext.flutter.inspector.setFlexFactor: (-32000) Server error
'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 205 pos 12: 'match != null': Expected #4      Eval.<anonymous closure>.setFlexFactor () to match RegExp: pattern=^#(\d+) +(.+) \((.+?):?(\d+){0,1}:?(\d+){0,1}\)$ flags=.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:205:12)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:51:28)
```

**Comment by kenzieschmoll** [comment]
No longer reproducible.
