### ISSUE TITLE
Error thrown from VmService on hot restart

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4193]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [Sentinel kind: Collected, valueAsString: <collected>] from getIsolate()
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1742:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2255:21)
#2      VmService.getIsolate (package:vm_service/src/vm_service.dart:1982:7)
#3      VmServiceWrapper.getIsolate (package:devtools_app/src/service/vm_service_wrapper.dart:261:49)
#4      IsolateManager._loadIsolateState (package:devtools_app/src/service/isolate_manager.dart:111:35)
#5      IsolateManager._registerIsolate (package:devtools_app/src/service/isolate_manager.dart:106:11)
#6      IsolateManager._handleIsolateEvent (package:devtools_app/src/service/isolate_manager.dart:140:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
@bkonyi

**Comment by bkonyi** [comment]
If you're calling `getIsolate` on the isolate ID from before the restart, this is WAI since it's been killed and replaced with a new isolate.
