### ISSUE TITLE
Failed assertion after hot restart

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#428]
I saw this in the output on the debugger pane when I clicked Hot Restart (using the gallery app).

```
restarted in 1.9s

flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a service extension callback for
flutter: "ext.flutter.inspector.getChildrenDetailsSubtree":
flutter: Id does not exist.
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      _WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:1239:7)
flutter: #1      _WidgetInspectorService._getChildrenDetailsSubtree (package:flutter/src/widgets/widget_inspector.dart:1614:34)
flutter: #2      _WidgetInspectorService._registerServiceExtensionWithArg.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:917:35)
flutter: <asynchronous suspension>
flutter: #3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:512:32)
flutter: <asynchronous suspension>
flutter: #4      _runExtension (dart:developer/runtime/lib/developer.dart:84:23)
flutter: #6      SemanticsConfiguration.elevation= (package:flutter/src/semantics/semantics.dart)
flutter: #7      _RenderPhysicalModelBase.describeSemanticsConfiguration (package:flutter/src/rendering/proxy_box.dart:1584:12)
flutter: #8      RenderObject._semanticsConfiguration (package:flutter/src/rendering/object.dart:2291:7)
flutter: #9      RenderObject.markNeedsSemanticsUpdate (package:flutter/src/rendering/object.dart:2354:41)
flutter: #10     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1095:5)
flutter: #11     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #13     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #14     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #16     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #17     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #19     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #20     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #22     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #23     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #24     _RenderStack&RenderBox&ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3039:14)
flutter: #25     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #26     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #28     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #29     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #31     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #32     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #34     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #35     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #37     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #38     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #40     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #41     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #43     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #44     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #45     _RenderStack&RenderBox&ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3039:14)
flutter: #46     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #47     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #48     _RenderTheatre.visitChildren (package:flutter/src/widgets/overlay.dart:558:14)
flutter: #49     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #50     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #52     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #53     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #55     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #56     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #58     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #59     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #61     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #62     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #64     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #65     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1097:13)
flutter: #66     _RenderView&RenderObject&RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:2773:14)
flutter: #67     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1096:5)
flutter: #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.performReassemble (package:flutter/src/rendering/binding.dart:348:18)
flutter: <asynchronous suspension>
flutter: #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.performReassemble (package:flutter/src/widgets/binding.dart:749:18)
flutter: #70     BindingBase.lockEvents (package:flutter/src/foundation/binding.dart:213:41)
flutter: #71     BindingBase.reassembleApplication (package:flutter/src/foundation/binding.dart:253:12)
flutter: #72     BindingBase.initServiceExtensions.<anonymous closure>.<anonymous closure> (package:flutter/src/foundation/binding.dart:174:19)
flutter: <asynchronous suspension>
flutter: #73     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:512:32)
flutter: <asynchronous suspension>
flutter: #74     _runExtension (dart:developer/runtime/lib/developer.dart:84:23)
flutter: #75     new ByteData._view (dart:typed_data/runtime/lib/typed_data_patch.dart:48:3)
flutter: (elided one frame from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by DanTup** [comment]
@jacob314 I can't reproduce this today - not sure if it's probably been fixed or just intermittent?

**Comment by jacob314** [comment]
I expect it is intermittent and reasonably rare. Moving to backlog unless we see other reports.
