### ISSUE TITLE
Exception thrown from ServiceExtensionCheckboxGroupButtonState

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4461]
flutter: [ERROR]: Bad state: Stream has already been listened to.
flutter: Bad state: Stream has already been listened to.
flutter: #3      _ServiceExtensionCheckboxGroupButtonState.initState (package:devtools_app/src/service/service_extension_widgets.dart:624)
flutter: #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5028)
flutter: #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4871)
flutter: #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3883)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3612)

Interesting to note that this was triggered when clicking on the "Highlight Repaints" button from the inspector, which does not have any checkboxes.

**Comment by kenzieschmoll** [comment]
Cannot reproduce. Closing.
