### ISSUE TITLE
Memory > Allocation Tracing: checkboxes are not clickable in profile mode

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4597]
For profile mode we need to show empty tab with message like 'Run application in debug mode to enable allocation tracing'.

```
#0      _MemoryChartPaneState.didChangeDependencies.<anonymous closure> (package:devtools_app/src/screens/memory/panes/chart/chart_pane.dart:119:46)
package:devtools_app/src/screens/memory/panes/chart/chart_pane.dart:119
#3      ChartState.build.<anonymous closure>.<anonymous closure> (package:devtools_app/src/charts/chart.dart:105:36)
package:devtools_app/src/charts/chart.dart:105
#3      VmServiceWrapper.setTraceClassAllocation (package:devtools_app/src/service/vm_service_wrapper.dart:660:18)
#4      AllocationProfileTracingIsolateState.setAllocationTracingForClass (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_tracing_view_controller.dart:173:21)
#5      AllocationProfileTracingViewController.setAllocationTracingForClass (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_tracing_view_controller.dart:316:33)
#6      _TraceCheckBoxColumn.build.<anonymous closure> (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_class_table.dart:46:26)
#3      VmServiceWrapper.setTraceClassAllocation (package:devtools_app/src/service/vm_service_wrapper.dart:660:18)
#4      AllocationProfileTracingIsolateState.setAllocationTracingForClass (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_tracing_view_controller.dart:173:21)
#5      AllocationProfileTracingViewController.setAllocationTracingForClass (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_tracing_view_controller.dart:316:33)
#6      _TraceCheckBoxColumn.build.<anonymous closure> (package:devtools_app/src/screens/memory/panes/allocation_tracing/allocation_profile_class_table.dart:46:26)
#3      VmServiceWrapper.setTraceClassAllocation (package:devtools_app/src/service/vm_service_wrapper.dart:660:18)
```

**Comment by polina-c** [comment]
@bkonyi

**Comment by bkonyi** [comment]
We're getting a `Compiler is disabled in AOT mode` response to `setTraceClassAllocation`, but it's not clear why we need a compiler available to enable tracing here. I'm following up with @rmacnak-google to determine whether or not enabling tracing requires code to be generated at runtime.

**Comment by bkonyi** [comment]
This should be resolved. See https://github.com/flutter/devtools/pull/7058
