### ISSUE TITLE
CPU profiler fails to process CPU samples

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#4643]
Steps to repro:

1. Connect devtools on macos to counter in debug mode on macos
2. Click CPU Profiler > Record
3. Increase counter in the app
4. Click record
5. See the error in devtools console:

```
flutter: DevTools version 2.19.0-dev.1.
#0      CodeRefPrivateViewExtension.function (package:devtools_app/src/screens/vm_developer/vm_service_private_extensions.dart:270:46)
#1      _CpuProfileTimelineTree._function (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:1082:20)
#2      _CpuProfileTimelineTree.resolvedUrl (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:1108:7)
#3      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:466:50)
#4      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#5      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#6      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#7      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#8      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#9      CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#10     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#11     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#12     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#13     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#14     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#15     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#16     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#17     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#18     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#19     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#20     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#21     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#22     CpuProfileData.generateFromCpuSamples.processStackFrame (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:473:9)
#23     CpuProfileData.generateFromCpuSamples (package:devtools_app/src/screens/profiler/cpu_profile_model.dart:481:5)
#24     CpuProfilerExtension.getCpuProfile (package:devtools_app/src/screens/profiler/cpu_profile_service.dart:59:42)
#25     CpuProfilerController.pullAndProcessProfile.pullAndProcessHelper (package:devtools_app/src/screens/profiler/cpu_profile_controller.dart:185:21)
#26     timeAsync (package:devtools_app/src/analytics/_analytics_stub.dart:61:5)
#27     CpuProfilerController.pullAndProcessProfile (package:devtools_app/src/screens/profiler/cpu_profile_controller.dart:201:7)
#28     ProfilerScreenController.stopRecording (package:devtools_app/src/screens/profiler/profiler_screen_controller.dart:90:5)
```

**Comment by bkonyi** [comment]
There were some changes to the service protocol that are needed by this change (see [this CL](https://dart-review.googlesource.com/c/sdk/+/264780)). Running `flutter upgrade` on `master` will resolve this issue.
