### ISSUE TITLE
Exception thrown when selecting network request

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#4870]
```
flutter: [ERROR]: Null check operator used on a null value
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building Expanded(flex: 1):
Null check operator used on a null value

The relevant error-causing widget was:
  Expanded
  Expanded:file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/lib/src/ui/tab.dart:233:9

When the exception was thrown, this was the stack:
#0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:177:53)
package:flutter/src/widgets/scroll_position.dart:177
#1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:390:19)
package:flutter/src/widgets/page_view.dart:390
#2      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:220:30)
package:flutter/src/widgets/page_view.dart:220
#3      _TabBarViewState.didUpdateWidget (package:flutter/src/material/tabs.dart:1465:23)
package:flutter/src/material/tabs.dart:1465
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:5142:55)
package:flutter/src/widgets/framework.dart:514
```

**Comment by srawlins** [comment]
Any reproduction steps? Maybe this can be considered obsolete, if we haven't been able to reproduce it (or seen user reports) in two years.
