### ISSUE TITLE
Logging page crashes when showing flutter web

### ISSUE THREAD

**Issue by efortuna** [flutter/devtools#527]
Jacob knows whole context -- this app causes the following error repeatedly in Chrome. 
Flutter web likely logged some null object in a different format than expecting, causing a cascade of failures. Repro is currently in a private repo. lmk and I can give you access: https://github.com/2d-inc/dev_rpg/tree/style-sphinx-with-web-update. 

Jacob suspects either Danny or Terry will be able to fix this.

```
Uncaught Invalid argument: null
    at Object.wrapException (http://localhost:55843/main.dart.js:1116:17)
    at Object.iae (http://localhost:55843/main.dart.js:1073:15)
    at LogWhenColumn.render$1 (http://localhost:55843/main.dart.js:36854:18)
    at Table._buildTableRows$3$currentRowIndex$firstRenderedRowInclusive$lastRenderedRowExclusive (http://localhost:55843/main.dart.js:41451:29)
    at Table._rebuildVirtualTable$0 (http://localhost:55843/main.dart.js:41370:31)
    at Table._rebuildTable$0 (http://localhost:55843/main.dart.js:41328:12)
    at Table__scheduleRebuild_closure.call$0 (http://localhost:55843/main.dart.js:41604:10)
    at SetStateMixin_setState_closure.call$1 (http://localhost:55843/main.dart.js:32519:27)
    at invokeClosure (http://localhost:55843/main.dart.js:1306:26)
    at http://localhost:55843/main.dart.js:1326:18
  | wrapException | @ | main.dart.js:1116
-- | -- | -- | --
  | iae | @ | main.dart.js:1073
  | render$1 | @ | main.dart.js:36854
  | _buildTableRows$3$currentRowIndex$firstRenderedRowInclusive$lastRenderedRowExclusive | @ | main.dart.js:41451
  | _rebuildVirtualTable$0 | @ | main.dart.js:41370
  | _rebuildTable$0 | @ | main.dart.js:41328
  | call$0 | @ | main.dart.js:41604
  | call$1 | @ | main.dart.js:32519
  | invokeClosure | @ | main.dart.js:1306
  | (anonymous) | @ | main.dart.js:1326
  | requestAnimationFrame (async) |   |  
  | _requestAnimationFrame$1 | @ | main.dart.js:25867
  | requestAnimationFrame$1 | @ | main.dart.js:25864
  | setState$1 | @ | main.dart.js:32513
  | _scheduleRebuild$0 | @ | main.dart.js:41297
  | setRows$1 | @ | main.dart.js:41278
  | _logging$_log$1 | @ | main.dart.js:36577
  | (anonymous) | @ | main.dart.js:36447
  | (anonymous) | @ | main.dart.js:3471
  | call$2 | @ | main.dart.js:17633
  | _asyncStartSync | @ | main.dart.js:3435
  | _handleExtensionEvent$body$LoggingScreen | @ | main.dart.js:36461
  | _logging$_handleExtensionEvent$1 | @ | main.dart.js:36423
  | (anonymous) | @ | VM563:3
  | runUnaryGuarded$1$2 | @ | main.dart.js:19701
  | _sendData$1 | @ | main.dart.js:19151
  | perform$1 | @ | main.dart.js:19351
  | handleNext$1 | @ | main.dart.js:19429
  | call$0 | @ | main.dart.js:19403
  | _microtaskLoop | @ | main.dart.js:3730
  | _startMicrotaskLoop | @ | main.dart.js:3736
  | call$1 | @ | main.dart.js:17494
  | invokeClosure | @ | main.dart.js:1306
  | (anonymous) | @ | main.dart.js:1326
  | childList (async) |   |  
  | call$1 | @ | main.dart.js:17504
  | _scheduleAsyncCallback | @ | main.dart.js:3749
  | _rootScheduleMicrotask | @ | main.dart.js:3965
  | scheduleMicrotask | @ | main.dart.js:3780
  | schedule$1 | @ | main.dart.js:19392
  | _addPending$1 | @ | main.dart.js:19142
  | _sendData$1 | @ | main.dart.js:18944
  | add$1 | @ | main.dart.js:18784
  | call$1 | @ | main.dart.js:40056
  | call$1 | @ | main.dart.js:26421
  | invokeClosure | @ | main.dart.js:1306
  | (anonymous) | @ | main.dart.js:1326

```

ran with:
`pub global run webdev serve --auto restart --debug --launch-in-chrome`

running webdev alpha2

**Comment by DanTup** [comment]
@efortuna looks like running this project needs some private forks from your GH account (listed in `dependency_overrides`) - are you able to give me read access to them? Thanks!

**Comment by efortuna** [comment]
actually you can take those other private repos out. I'll push an update.

**Comment by DanTup** [comment]
Ah, cool. Seems like @devoncarew just landed a fix anyway though :)
