### ISSUE TITLE
Inspector throws exception when connecting to a paused application

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5345]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:devtools_app/src/shared/diagnostics/inspector_service.dart': Failed assertion: line 415 pos 12: 'useDaemonApi': is not true.
inspector_service.dart:415
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      InspectorService._addPubRootDirectories
inspector_service.dart:415
#3      InspectorService.addPubRootDirectories
inspector_service.dart:405
#4      InspectorPreferencesController.addPubRootDirectories.<anonymous closure>
preferences.dart:239
#5      InspectorPreferencesController._customPubRootDirectoryBusyTracker
preferences.dart:307
#6      InspectorPreferencesController.addPubRootDirectories
preferences.dart:235
#7      InspectorPreferencesController.loadCustomPubRootDirectories.<anonymous closure>
preferences.dart:292
<asynchronous suspension>
#8      InspectorPreferencesController._customPubRootDirectoryBusyTracker
preferences.dart:307
<asynchronous suspension>
#9      InspectorPreferencesController.loadCustomPubRootDirectories
preferences.dart:287
<asynchronous suspension>
#10     InspectorPreferencesController._handleConnectionToNewService
preferences.dart:203
<asynchronous suspension>
```

**Comment by kenzieschmoll** [comment]
This issue appears to be resolved. The relevant methods in inspector_service.dart (such as _addPubRootDirectories) now use waitUntilNotPaused() to ensure the application is in a state where Daemon API calls can be safely made, which prevents the reported assertion failure.
