### ISSUE TITLE
Zone mismatch error when running DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5458]
@CoderDake is this related to any of the zone work you've been looking at?
```
flutter: [ERROR]: [FlutterError]: Zone mismatch.
The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown during runApp:
Zone mismatch.
The Flutter bindings were initialized in a different zone than is now being used. This will likely
cause confusion and bugs as any zone-specific configuration will inconsistently use the
configuration of the original binding initialization zone or this zone based on hard-to-predict
factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling
`runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are
initialized (i.e. as the first statement in `void main() { }`).

When the exception was thrown, this was the stack:
#0      BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:484:29)
#1      BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:489:6)
#2      runApp (package:flutter/src/widgets/binding.dart:1062:18)
#3      runDevTools.<anonymous closure> (package:devtools_app/initialization.dart:69:5)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by CoderDake** [comment]
Looks like we got lucky and this was added 4 days ago.
We can use it to assert that we aren't calling ensureInitialized in the wrong place :D
https://github.com/flutter/flutter/pull/122836/files
