### ISSUE TITLE
Test debugging from IntelliJ broken

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#55]
Debugging integration_test.dart from IntelliJ fails to connect to observatory. 

Running the test from IntelliJ works fine. It also runs successfully from command line using both `dart test/integration_test.dart ` as well as `pub run test/integration_test.dart`.

**When debugging, output of stdout from WebdevFixture.create()**
```
Observatory server failed to start after 1 tries
Observatory server failed to start after 2 tries
...
Observatory server failed to start after 11 tries
Could not start Observatory HTTP server:
SocketException: Failed to create server socket (OS Error: Address already in use, errno = 48), address = localhost, port = 57412
#0      _NativeSocket.bind (dart:io/runtime/binsocket_patch.dart:573:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1166:26)
#2      _ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1422:29)
#3      ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1413:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2524:25)
#5      HttpServer.bind (dart:_http:364:19)
#6      Server.startup.poll (dart:vmservice_io/server.dart:352:36)
<asynchronous suspension>
#7      Server.startup (dart:vmservice_io/server.dart:364:23)
<asynchronous suspension>
#8      main (dart:vmservice_io:253:12)

```

**Comment by kenzieschmoll** [comment]
Running `pub run webdev serve web` from command line is successful, but the same command attempt from WebdevFixture.create() produces the stdout above.

**Comment by kenzieschmoll** [comment]
Fixed by https://github.com/flutter/devtools/pull/56

**Comment by kenzieschmoll** [comment]
Still seeing this in certain places.

**Comment by kenzieschmoll** [comment]
Verified debugging DevTools test from IntelliJ works fine. Closing as obsolete.
