### ISSUE TITLE
Detect Leaks: Analyze and Download in Flutter DevTools errors out

### ISSUE THREAD

**Issue by domesticmouse** [flutter/devtools#5901]
```console
A Dart VM Service on macOS is available at: http://127.0.0.1:55886/_KYFjcKaAIQ=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:55886/_KYFjcKaAIQ=/
flutter: leak_tracker: 0 memory leak(s): not disposed: 0, not GCed: 0, GCed late: 0
flutter: leak_tracker: Error handling leak tracking request from DevTools to application.
flutter: leak_tracker: Null check operator used on a null value
flutter: leak_tracker: #0      envelopeByType (package:leak_tracker/src/devtools_integration/_protocol.dart:159:62)
#1      sealEnvelope (package:leak_tracker/src/devtools_integration/_protocol.dart:58:23)
#2      ResponseFromApp.toJson (package:leak_tracker/src/devtools_integration/delivery.dart:55:7)
#3      ResponseFromApp.toServiceResponse (package:leak_tracker/src/devtools_integration/delivery.dart:51:20)
#4      setupDevToolsIntegration.handler (package:leak_tracker/src/devtools_integration/_registration.dart:51:14)
#5      _RootZone.runBinary (dart:async/zone.dart:1666:54)
#6      _RootZone.bindBinaryCallback.<anonymous closure> (dart:async/zone.dart:1625:33)
#7      _runExtension (dart:developer-patch/developer.dart:91:23)
```

Obligatory flutter doctor output:

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en)
    • Flutter version 3.10.4 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 682aa387cf (6 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by kenzieschmoll** [comment]
@polina-c

**Comment by polina-c** [comment]
leak_tracker support in DevTools is not priority at the moment. 
First CUJ to enable is regression testing for memory leaks.
See details: https://github.com/flutter/flutter/issues/134787
