### ISSUE TITLE
RPC framing error in perfetto

### ISSUE THREAD

**Issue by filiph** [flutter/devtools#6007]
Trying to see Timeline Events and getting this after many seconds of loading:

```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: http://127.0.0.1:9101

Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270987:20
onRpcResponseBytes@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270949:19
onMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:271348:16


v33.0-a38eb95ac a38eb95acf21b58d8f34393480f8aec1120c6115
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0


---------------------------------------
Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270987:20
onRpcResponseBytes@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270949:19
onMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:271348:16


v33.0-a38eb95ac a38eb95acf21b58d8f34393480f8aec1120c6115
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0


---------------------------------------
Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270987:20
onRpcResponseBytes@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270949:19
onMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:271348:16


v33.0-a38eb95ac a38eb95acf21b58d8f34393480f8aec1120c6115
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0


---------------------------------------
Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270987:20
onRpcResponseBytes@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270949:19
onMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:271348:16


v33.0-a38eb95ac a38eb95acf21b58d8f34393480f8aec1120c6115
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0


---------------------------------------
Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270987:20
onRpcResponseBytes@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270949:19
onMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:271348:16


v33.0-a38eb95ac a38eb95acf21b58d8f34393480f8aec1120c6115
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0


---------------------------------------
Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270987:20
onRpcResponseBytes@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:270949:19
onMessage@http://127.0.0.1:9101/assets/packages/perfetto_compiled/dist/v33.0-a38eb95ac/frontend_bundle.js:271348:16


v33.0-a38eb95ac a38eb95acf21b58d8f34393480f8aec1120c6115
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0
```

<img width="1608" alt="Screenshot 2023-07-10 at 10 50 49" src="https://github.com/flutter/devtools/assets/919717/fb4a8529-a6be-44c9-86d0-e05a21833594">

Exported data: 
[dart_devtools_2023-07-10_10 51 13.136.json.zip](https://github.com/flutter/devtools/files/11999771/dart_devtools_2023-07-10_10.51.13.136.json.zip)

___
**DevTools version**: 2.23.1
**Connected Device**:
CPU / OS: arm64 (64 bit) macos
Dart Version: 3.0.2
Flutter Version: 3.10.2 / stable
Framework / Engine: 9cd3d0d9ff / 90fa3ae28f
Connected app type: Flutter native (profile build)

**Comment by FaFre** [comment]
Got a similar issue with current stable while trying to view Timeline Events:

```
Viewed on: http://127.0.0.1:9101

Uncaught Error: RPC framing error
Error: RPC framing error
    at WasmEngineProxy.onRpcResponseMessage (http://127.0.0.1:9101/assets/packages/perfetto_ui_compiled/dist/v34.0-16f63abe3/frontend_bundle.js:273522:20)
    at WasmEngineProxy.onRpcResponseBytes (http://127.0.0.1:9101/assets/packages/perfetto_ui_compiled/dist/v34.0-16f63abe3/frontend_bundle.js:273484:19)
    at WasmEngineProxy.onMessage (http://127.0.0.1:9101/assets/packages/perfetto_ui_compiled/dist/v34.0-16f63abe3/frontend_bundle.js:273871:16)

v34.0-16f63abe3 16f63abe33753ce31d9b29e3a4281a5435773fc7
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36
```

**Comment by kenzieschmoll** [comment]
@FaFre can you run `flutter doctor -v` and paste the results here? Thanks.
