### ISSUE TITLE
Call to `addPubRootDirectories` throws on hot restart

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6357]
```
flutter: [ERROR]: [zoneGuarded]: ext.flutter.inspector.addPubRootDirectories: (-32601) Unknown method "ext.flutter.inspector.addPubRootDirectories".
flutter: [ERROR]: [PlatformDispatcher]: ext.flutter.inspector.addPubRootDirectories: (-32601) Unknown method "ext.flutter.inspector.addPubRootDirectories".
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ext.flutter.inspector.addPubRootDirectories: (-32601) Unknown method "ext.flutter.inspector.addPubRootDirectories".
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1930:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2499:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2470:14)
#3      VmServiceWrapper.callServiceExtension (package:devtools_app/src/service/vm_service_wrapper.dart:162:18)
#4      InspectorServiceBase.invokeServiceMethodDaemonNoGroup (package:devtools_app/src/shared/diagnostics/inspector_service.dart:176:57)
<asynchronous suspension>
#5      InspectorService.addPubRootDirectories (package:devtools_app/src/shared/diagnostics/inspector_service.dart:422:5)
<asynchronous suspension>
#6      InspectorPreferencesController.addPubRootDirectories.<anonymous closure> (package:devtools_app/src/shared/preferences.dart:287:7)
<asynchronous suspension>
#7      InspectorPreferencesController._customPubRootDirectoryBusyTracker (package:devtools_app/src/shared/preferences.dart:355:7)
<asynchronous suspension>
#8      InspectorPreferencesController.addPubRootDirectories (package:devtools_app/src/shared/preferences.dart:283:5)
<asynchronous suspension>
#9      InspectorPreferencesController.loadCustomPubRootDirectories.<anonymous closure> (package:devtools_app/src/shared/preferences.dart:340:9)
<asynchronous suspension>
#10     InspectorPreferencesController._customPubRootDirectoryBusyTracker (package:devtools_app/src/shared/preferences.dart:355:7)
<asynchronous suspension>
#11     InspectorPreferencesController.loadCustomPubRootDirectories (package:devtools_app/src/shared/preferences.dart:335:5)
<asynchronous suspension>

```

**Comment by kenzieschmoll** [comment]
![Screenshot 2023-09-15 at 10 38 22 AM](https://github.com/flutter/devtools/assets/43759233/f2c31ecf-cf25-4138-8084-63c0736ecfc7)
