### ISSUE TITLE
DevTools set `debugDefaultTargetPlatformOverride` but don't reset it, causing assertions to be broken

### ISSUE THREAD

**Issue by bartekpacia** [flutter/devtools#6719]
The DevTools call `FoundationServiceExtensions.platformOverride`, which [modifies](https://github.com/flutter/flutter/blob/f70a01c69165561d7754a6882a124d11fe6da4e6/packages/flutter/lib/src/foundation/binding.dart#L568C9-L568C9) [`debugDefaultTargetPlatformOverride`](https://github.com/flutter/flutter/blob/f70a01c69165561d7754a6882a124d11fe6da4e6/packages/flutter/lib/src/foundation/platform.dart#L98).

This causes tests to fail because the assertion in `TestWidgetsFlutterBinding._runTestBody()` is violated:

https://github.com/flutter/flutter/blob/0cdb3bf582f00cbb9bc4a3701263ab655b09db69/packages/flutter_test/lib/src/binding.dart#L1031-L1035

The exact value that is changed is `debugDefaultTargetPlatformOverride`:

https://github.com/flutter/flutter/blob/0cdb3bf582f00cbb9bc4a3701263ab655b09db69/packages/flutter/lib/src/foundation/debug.dart#L28-L39

**Comment by polina-c** [comment]
Can you provide steps to repro the assertion failure?

**Comment by bartekpacia** [comment]
Sure, will do it next week.

**Comment by bartekpacia** [comment]
## Repro

Make sure you're using the latest stable Flutter 3.16.0.

### Working as intended

This will demonstrate that [the workaround](https://github.com/leancodepl/patrol/issues/1930) works.

1. `git clone https://github.com/leancodepl/patrol.git && `cd patrol`
2. `dart pub global activate --source path packages/patrol_cli && patrol`
3. `cd packages/patrol/exampe` - here lives the example app
4. `patrol develop --target integration_test/example_test.dart`
5. Flutter DevTools should automatically open in the default browser with Patrol DevTools extension opened.
6. Hot Restart a few times - either by tapping "R" key in `patrol develop` in terminal or by clicking a Hot Restart button in the DevTools.

### Failing

1. `git checkout devtools_bug_repro` ([this branch](https://github.com/leancodepl/patrol/pull/1934)). The workaround for this bug is removed on the `devtools_bug_repro` branch.
2. Recompile the CLI (run this from repo root):

  ```
  dart pub global activate --source path packages/patrol_cli && patrol
  ```

3. `patrol develop --target integration_test/example_test.dart`
4. Restart the test a few times – either by "R" in terminal or in DevTOols.
5. Notice the assertion being violated when the test ends executing:

  ```
  Patrol (native): openApp() started
  Patrol (native): openApp() succeeded
  ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following assertion was thrown running a test:
  The value of a foundation debug variable was changed by the test.

  When the exception was thrown, this was the stack:
  #0      debugAssertAllFoundationVarsUnset.<anonymous closure> (package:flutter/src/foundation/debug.dart:34:7)
  #1      debugAssertAllFoundationVarsUnset (package:flutter/src/foundation/debug.dart:37:4)
  #2      TestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1049:12)
  #3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1030:7)
  <asynchronous suspension>
  #4      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
  <asynchronous suspension>

  The test description was:
    counter state is the same after going to Home and switching apps
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  00:05 +0: example_test counter state is the same after going to Home and switching apps [E]
    Test failed. See exception logs above.
    The test description was: counter state is the same after going to Home and switching apps

  00:05 +0 -1: Some tests failed.
  ```
6. Now kill the DevTools (close the browser tab). Restart a few times by tapping "R" on keyboard in `patrol develop`'s process in terminal. Notice no assertion is being violated.

**Comment by kenzieschmoll** [comment]
DevTools doesn't have an understanding of "beginning" or "end" of test. It just knows it has a running Dart VM that it can interact with. The fix for this issue may actually be on the Flutter side if there is something in the test shutdown that is not happening like in the non-test environment.

**Comment by bartekpacia** [comment]
> We should trace where in DevTools this is happening and why.

I agree. Unfortunately I couldn't find the place in DevTools code where that extension is called.

> The fix for this issue may actually be on the Flutter side if there is something in the test shutdown that is not happening like in the non-test environment.

"Something in the test shutdown not happening in non-test environment" - this sounds like a test-specific Binding class, e.g. [`TestWidgetsFlutterBinding`](https://github.com/flutter/flutter/blob/3.16.0/packages/flutter_test/lib/src/binding.dart#L181). E.g. [`TestWidgetsFlutterBinding._verifyInvariants`](https://github.com/flutter/flutter/blob/3.16.0/packages/flutter_test/lib/src/binding.dart#L1050-L1053) - but that's actually source of this problem.
