### ISSUE TITLE
Cannot open Timeline Events page on Windows

### ISSUE THREAD

**Issue by Markus43** [flutter/devtools#6887]
I'd like to profile my Windows application from VS Code using Devtools' Performance view.

Whenever I select the page, I get a popup with the following error:
Oops, something went wrong. Please file a bug.
✕
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: http://127.0.0.1:9100

SecurityError: Failed to execute 'getDevices' on 'USB': Access to the feature "usb" is disallowed by permissions policy.
Error: Failed to execute 'getDevices' on 'USB': Access to the feature "usb" is disallowed by permissions policy.
    at AdbOverWebUsb.<anonymous> (http://127.0.0.1:9100/assets/packages/perfetto_ui_compiled/dist/v33.0-1838a06af/frontend_bundle.js:290487:40)
    at Generator.next (<anonymous>)
    at http://127.0.0.1:9100/assets/packages/perfetto_ui_compiled/dist/v33.0-1838a06af/frontend_bundle.js:156:71
    at new Promise (<anonymous>)
    at Object.__awaiter (http://127.0.0.1:9100/assets/packages/perfetto_ui_compiled/dist/v33.0-1838a06af/frontend_bundle.js:152:12)
    at AdbOverWebUsb.getPairedDevices (http://127.0.0.1:9100/assets/packages/perfetto_ui_compiled/dist/v33.0-1838a06af/frontend_bundle.js:290485:26)
    at http://127.0.0.1:9100/assets/packages/perfetto_ui_compiled/dist/v33.0-1838a06af/frontend_bundle.js:310036:59
    at Generator.next (<anonymous>)
    at http://127.0.0.1:9100/assets/packages/perfetto_ui_compiled/dist/v33.0-1838a06af/frontend_bundle.js:156:71
    at new Promise (<anonymous>)

v33.0-1838a06af 1838a06af94f1b9897907d168408f399e23fbc18
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.84.2 Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36

flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3570], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.2)
[√] VS Code (version 1.84.2)
[√] Connected device (1 available)
[√] Network resources

• No issues found!

The weird thing here is that this seems to be an error coming from android support, but I have completely disabled android via 
`flutter config --no-enable-android` in this environment.

**Comment by Finni123** [comment]
Any update? I have the same problem

**Comment by pamafe1976** [comment]
I had that same problem while debugging my Android app, and found it to be related to this line in android/gradle.properties

extra-gen-snapshot-options=--obfuscate

Works fine after removing it.

**Comment by FluffyBunniesTasteTheBest** [comment]
Same here when trying to profile an Android app in VS Code 1.92.2 with DevTools 2.37.2 running on MacOS.

Obfuscate option not set at gradle.properties.

**Comment by jnorkus** [comment]
I'm having the same issue. I can't inspect the Timeline Events on Android.
