### ISSUE TITLE
Reporting error: Error collecting raster stats: _flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame was rendered

### ISSUE THREAD

**Issue by umar-hunch** [flutter/devtools#7222]
Stack trace:
Error
    at Object.qb (http://127.0.0.1:9101/main.dart.js:6162:18)
    at http://127.0.0.1:9101/main.dart.js:160270:5
    at bDd.a (http://127.0.0.1:9101/main.dart.js:4771:62)
    at bDd.$2 (http://127.0.0.1:9101/main.dart.js:56657:14)
    at Object.m (http://127.0.0.1:9101/main.dart.js:4757:10)
    at z9.aD0 (http://127.0.0.1:9101/main.dart.js:160284:10)
    at z9.cb (http://127.0.0.1:9101/main.dart.js:160263:25)
    at z9.jD (http://127.0.0.1:9101/main.dart.js:160248:13)
    at ik.jD (http://127.0.0.1:9101/main.dart.js:88607:44)
    at http://127.0.0.1:9101/main.dart.js:100371:14
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.28.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: arm64 (64 bit) android
Connected app type: Flutter native (profile build)
Dart Version: 3.2.2
Flutter Version: 3.16.2 / stable
Framework / Engine: 9e1c857886 / cf7a9d0800

**Comment by CoderDake** [comment]
Duplicate of https://github.com/flutter/devtools/issues/6992
