### ISSUE TITLE
[Flaky integration test] `packages/devtools_app/integration_test/test/live_connection/service_extensions_test.dart`: "A SemanticsHandle was active at the end of the test."

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#8107]
Splitting this issue out of https://github.com/flutter/devtools/issues/8013 to handle this particular test failure. 

DevTools itself never creates a `SemanticsHandler`, so I'm guessing this failure is actually coming from the framework. Possibly related to https://github.com/flutter/flutter/issues/121640

Example test runs:
* https://github.com/flutter/devtools/actions/runs/10097795429/job/27923501767
* https://github.com/flutter/devtools/actions/runs/9767563965/job/26963163313

Failure message:
```
Failure Details:
Failure in method: can call services and service extensions
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test (but after the
test had completed):
A SemanticsHandle was active at the end of the test.
All SemanticsHandle instances must be disposed by calling
dispose() on the SemanticsHandle.

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
packages/flutter_test/src/test_text_input_key_handler.dart.js 10314:19       [_verifySemanticsHandlesWereDisposed]
packages/flutter_test/src/test_text_input_key_handler.dart.js 10308:50       [_endOfTestVerifications]
packages/flutter_test/src/test_text_input_key_handler.dart.js 11295:11       _runTestBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 47:50           <fn>
dart-sdk/lib/async/zone.dart 1407:47                                         _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                         runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                    <fn>
dart-sdk/lib/async/zone.dart 1399:13                                         _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                         run
dart-sdk/lib/async/zone.dart 1209:7                                          runGuarded
dart-sdk/lib/async/zone.dart 1249:23                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 183:7           <fn>
═════════════════════════════════════════════════════════════════


#0      IntegrationTestRunner.run.runTest (package:devtools_shared/src/test/integration_test_runner.dart:138:11)
<asynchronous suspension>
#1      IntegrationTestRunner.run (package:devtools_shared/src/test/integration_test_runner.dart:143:5)
<asynchronous suspension>
#2      runFlutterIntegrationTest (file:///Users/runner/work/devtools/devtools/packages/devtools_app/integration_test/test_infra/run/run_test.dart:66:5)
<asynchronous suspension>
#3      _runTest (file:///Users/runner/work/devtools/devtools/packages/devtools_app/integration_test/run_tests.dart:81:3)
<asynchronous suspension>
#4      runOneOrManyTests (package:devtools_shared/src/test/integration_test_runner.dart:330:9)
<asynchronous suspension>
#5      main (file:///Users/runner/work/devtools/devtools/packages/devtools_app/integration_test/run_tests.dart:53:3)
<asynchronous suspension>
```

**Comment by elliette** [comment]
Still seeing this despite https://github.com/flutter/devtools/pull/8108

https://github.com/flutter/devtools/actions/runs/10183112325/job/28167343528?pr=8115
