### ISSUE TITLE
can open the devtools debugger in opera browser

### ISSUE THREAD

**Issue by AkshitOstwal** [flutter/devtools#853]
```
Failed to launch browser: ProcessException: The system cannot find the file specified.

  Command: .\Google\Chrome\Application\chrome.exe http://127.0.0.1:51779/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A51646%2FQmsulfhsCFI%3D%2F
#0      Chrome._startProcess (package:browser_launcher/src/chrome.dart:128:12)
<asynchronous suspension>
#1      Chrome.start (package:browser_launcher/src/chrome.dart:120:11)
<asynchronous suspension>
#2      registerLaunchDevToolsService.<anonymous closure> (package:devtools_server/src/server.dart:238:24)
<asynchronous suspension>
#3      VmService._routeRequest (package:vm_service_lib/vm_service_lib.dart:1631:39)
<asynchronous suspension>
#4      VmService._processRequest (package:vm_service_lib/vm_service_lib.dart:1609:25)
<asynchronous suspension>
#5      VmService._processMessageStr (package:vm_service_lib/vm_service_lib.dart:1577:9)
#6      VmService._processMessage (package:vm_service_lib/vm_service_lib.dart:1535:7)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#12     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#17     _StreamController._add (dart:async/stream_controller.dart:640:7)
#18     _StreamController.add (dart:async/stream_controller.dart:586:5)
#19     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1138:21)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#26     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#31     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#32     _StreamController._add (dart:async/stream_controller.dart:640:7)
#33     _StreamController.add (dart:async/stream_controller.dart:586:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#39     _StreamController._add (dart:async/stream_controller.dart:640:7)
#40     _StreamController.add (dart:async/stream_controller.dart:586:5)
#41     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

i dont have chrome installed .
i usually use opera browser or mozilla .
i can't use opera for devtoos debugger
the problem is here in command where it tries to open chrome, it should be opened default browser

```
 Command: .\Google\Chrome\Application\chrome.exe http://127.0.0.1:51779/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A51646%2FQmsulfhsCFI%3D%2F
```

**Comment by jacob314** [comment]
Unfortunately the devtools app currently requires chrome as that is the only browser we test it with.
We should however display a better error message from devtools server when Chrome is not found. At some point we will port the devtools app to flutter web at which point we will be able to test in multiple browsers.

Opera might indeed work fine even though we haven't tested it. If DevTools works well in Opera let us know and we can tweak the devtools server to launch opera if Chrome is not found.

**Comment by nocategory** [comment]
Same error occurs with different versions of Chrome other than stable (Dev in my case, for example).
The solution I got for now is really to just copy the url from the Command in logs.

**Comment by repentsinner** [comment]
Similar issue as @nocategory - on Mac I keep Chrome in `~/Applications` instead of `/Applications` to be able to update the Chrome instance w/o disrupting different user accounts - globally installed apps are terrible for this. If I open the link manually in Chrome it works fine, DevTools just can't find the correct instance.

**Comment by jacob314** [comment]
The port to Flutter web will help our browser compatibility.

**Comment by kenzieschmoll** [comment]
DevTools can be opened in Opera browser - just tested locally. Related: https://github.com/flutter/devtools/issues/2357
